/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1MA8tVtTQ6ARhYAYML2fXH
// Component: uEZTlYNpPear

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/projectcss
import sty from "./PlasmicContactSectionFooterTop.module.css"; // plasmic-import: uEZTlYNpPear/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: Xfpv3asY6zW4/icon

createPlasmicElementProxy;

export type PlasmicContactSectionFooterTop__VariantMembers = {};
export type PlasmicContactSectionFooterTop__VariantsArgs = {};
type VariantPropType = keyof PlasmicContactSectionFooterTop__VariantsArgs;
export const PlasmicContactSectionFooterTop__VariantProps =
  new Array<VariantPropType>();

export type PlasmicContactSectionFooterTop__ArgsType = {};
type ArgPropType = keyof PlasmicContactSectionFooterTop__ArgsType;
export const PlasmicContactSectionFooterTop__ArgProps =
  new Array<ArgPropType>();

export type PlasmicContactSectionFooterTop__OverridesType = {
  root?: Flex__<"div">;
  columns?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  h2?: Flex__<"h2">;
  textbox?: Flex__<"input">;
  textbox2?: Flex__<"input">;
  textbox3?: Flex__<"input">;
  textbox4?: Flex__<"input">;
  textarea?: Flex__<"textarea">;
  link?: Flex__<"a"> & Partial<LinkProps>;
};

export interface DefaultContactSectionFooterTopProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicContactSectionFooterTop__RenderFunc(props: {
  variants: PlasmicContactSectionFooterTop__VariantsArgs;
  args: PlasmicContactSectionFooterTop__ArgsType;
  overrides: PlasmicContactSectionFooterTop__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "textbox.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      },
      {
        path: "textbox2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      },
      {
        path: "textbox3.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      },
      {
        path: "textbox4.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      },
      {
        path: "textarea.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"columns"}
        data-plasmic-override={overrides.columns}
        className={classNames(projectcss.all, sty.columns)}
      >
        <div className={classNames(projectcss.all, sty.column__bvT9C)}>
          <PlasmicImg__
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={"100%"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"100%"}
            loading={"lazy"}
            src={{
              src: "/plasmic/amir_ghahari_website/images/map27890521920Jpg.jpg",
              fullWidth: 1920,
              fullHeight: 1280,
              aspectRatio: undefined
            }}
          />
        </div>
        <div className={classNames(projectcss.all, sty.column__tKjpi)}>
          <h2
            data-plasmic-name={"h2"}
            data-plasmic-override={overrides.h2}
            className={classNames(
              projectcss.all,
              projectcss.h2,
              projectcss.__wab_text,
              sty.h2
            )}
          >
            {"Get in touch."}
          </h2>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__jBiYs
            )}
          >
            {
              "A euismod eros a hendrerit tristique suscipit sit aptent dolor adipiscing inceptos cras ullamcorper a vivamus parturient."
            }
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__dCk7)}>
            <div className={classNames(projectcss.all, sty.freeBox__rwiCs)}>
              <input
                data-plasmic-name={"textbox"}
                data-plasmic-override={overrides.textbox}
                className={classNames(
                  projectcss.all,
                  projectcss.input,
                  sty.textbox
                )}
                onChange={async (...eventArgs: any) => {
                  (e => {
                    generateStateOnChangeProp($state, ["textbox", "value"])(
                      e.target.value
                    );
                  }).apply(null, eventArgs);
                }}
                placeholder={"First Name"}
                ref={ref => {
                  $refs["textbox"] = ref;
                }}
                size={1}
                type={"text"}
                value={
                  generateStateValueProp($state, ["textbox", "value"]) ?? ""
                }
              />

              <input
                data-plasmic-name={"textbox2"}
                data-plasmic-override={overrides.textbox2}
                className={classNames(
                  projectcss.all,
                  projectcss.input,
                  sty.textbox2
                )}
                onChange={async (...eventArgs: any) => {
                  (e => {
                    generateStateOnChangeProp($state, ["textbox2", "value"])(
                      e.target.value
                    );
                  }).apply(null, eventArgs);
                }}
                placeholder={"Last Name"}
                ref={ref => {
                  $refs["textbox2"] = ref;
                }}
                size={1}
                type={"text"}
                value={
                  generateStateValueProp($state, ["textbox2", "value"]) ?? ""
                }
              />
            </div>
            <input
              data-plasmic-name={"textbox3"}
              data-plasmic-override={overrides.textbox3}
              className={classNames(
                projectcss.all,
                projectcss.input,
                sty.textbox3
              )}
              onChange={async (...eventArgs: any) => {
                (e => {
                  generateStateOnChangeProp($state, ["textbox3", "value"])(
                    e.target.value
                  );
                }).apply(null, eventArgs);
              }}
              placeholder={"Email address"}
              ref={ref => {
                $refs["textbox3"] = ref;
              }}
              size={1}
              type={"text"}
              value={
                generateStateValueProp($state, ["textbox3", "value"]) ?? ""
              }
            />

            <input
              data-plasmic-name={"textbox4"}
              data-plasmic-override={overrides.textbox4}
              className={classNames(
                projectcss.all,
                projectcss.input,
                sty.textbox4
              )}
              onChange={async (...eventArgs: any) => {
                (e => {
                  generateStateOnChangeProp($state, ["textbox4", "value"])(
                    e.target.value
                  );
                }).apply(null, eventArgs);
              }}
              placeholder={"Phone number"}
              ref={ref => {
                $refs["textbox4"] = ref;
              }}
              size={1}
              type={"text"}
              value={
                generateStateValueProp($state, ["textbox4", "value"]) ?? ""
              }
            />

            <textarea
              data-plasmic-name={"textarea"}
              data-plasmic-override={overrides.textarea}
              className={classNames(
                projectcss.all,
                projectcss.textarea,
                sty.textarea
              )}
              onChange={async (...eventArgs: any) => {
                (e => {
                  generateStateOnChangeProp($state, ["textarea", "value"])(
                    e.target.value
                  );
                }).apply(null, eventArgs);
              }}
              placeholder={"Message"}
              ref={ref => {
                $refs["textarea"] = ref;
              }}
              value={
                generateStateValueProp($state, ["textarea", "value"]) ?? ""
              }
            />

            <PlasmicLink__
              data-plasmic-name={"link"}
              data-plasmic-override={overrides.link}
              className={classNames(projectcss.all, projectcss.a, sty.link)}
              component={Link}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__emuKf)}
                  role={"img"}
                />
              ) : null}
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__oyg5D
                )}
              >
                {"Send"}
              </div>
              {false ? (
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__etHzt)}
                  role={"img"}
                />
              ) : null}
            </PlasmicLink__>
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "columns",
    "img",
    "h2",
    "textbox",
    "textbox2",
    "textbox3",
    "textbox4",
    "textarea",
    "link"
  ],
  columns: [
    "columns",
    "img",
    "h2",
    "textbox",
    "textbox2",
    "textbox3",
    "textbox4",
    "textarea",
    "link"
  ],
  img: ["img"],
  h2: ["h2"],
  textbox: ["textbox"],
  textbox2: ["textbox2"],
  textbox3: ["textbox3"],
  textbox4: ["textbox4"],
  textarea: ["textarea"],
  link: ["link"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  columns: "div";
  img: typeof PlasmicImg__;
  h2: "h2";
  textbox: "input";
  textbox2: "input";
  textbox3: "input";
  textbox4: "input";
  textarea: "textarea";
  link: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicContactSectionFooterTop__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicContactSectionFooterTop__VariantsArgs;
    args?: PlasmicContactSectionFooterTop__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicContactSectionFooterTop__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicContactSectionFooterTop__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicContactSectionFooterTop__ArgProps,
          internalVariantPropNames: PlasmicContactSectionFooterTop__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicContactSectionFooterTop__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicContactSectionFooterTop";
  } else {
    func.displayName = `PlasmicContactSectionFooterTop.${nodeName}`;
  }
  return func;
}

export const PlasmicContactSectionFooterTop = Object.assign(
  // Top-level PlasmicContactSectionFooterTop renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    columns: makeNodeComponent("columns"),
    img: makeNodeComponent("img"),
    h2: makeNodeComponent("h2"),
    textbox: makeNodeComponent("textbox"),
    textbox2: makeNodeComponent("textbox2"),
    textbox3: makeNodeComponent("textbox3"),
    textbox4: makeNodeComponent("textbox4"),
    textarea: makeNodeComponent("textarea"),
    link: makeNodeComponent("link"),

    // Metadata about props expected for PlasmicContactSectionFooterTop
    internalVariantProps: PlasmicContactSectionFooterTop__VariantProps,
    internalArgProps: PlasmicContactSectionFooterTop__ArgProps
  }
);

export default PlasmicContactSectionFooterTop;
/* prettier-ignore-end */
