/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1MA8tVtTQ6ARhYAYML2fXH
// Component: Lw-gkCDZoDWc

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/projectcss
import sty from "./PlasmicWebsiteHeader.module.css"; // plasmic-import: Lw-gkCDZoDWc/css

createPlasmicElementProxy;

export type PlasmicWebsiteHeader__VariantMembers = {};
export type PlasmicWebsiteHeader__VariantsArgs = {};
type VariantPropType = keyof PlasmicWebsiteHeader__VariantsArgs;
export const PlasmicWebsiteHeader__VariantProps = new Array<VariantPropType>();

export type PlasmicWebsiteHeader__ArgsType = {};
type ArgPropType = keyof PlasmicWebsiteHeader__ArgsType;
export const PlasmicWebsiteHeader__ArgProps = new Array<ArgPropType>();

export type PlasmicWebsiteHeader__OverridesType = {
  headerNavbar?: Flex__<"div">;
  navbarContainer?: Flex__<"div">;
  homeButtonLink?: Flex__<"a"> & Partial<LinkProps>;
  img?: Flex__<typeof PlasmicImg__>;
  pagesLinksContainer?: Flex__<"div">;
  aboutLink?: Flex__<"a"> & Partial<LinkProps>;
  skills?: Flex__<"a"> & Partial<LinkProps>;
  resume?: Flex__<"a"> & Partial<LinkProps>;
  projects?: Flex__<"a"> & Partial<LinkProps>;
  contact?: Flex__<"a"> & Partial<LinkProps>;
};

export interface DefaultWebsiteHeaderProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicWebsiteHeader__RenderFunc(props: {
  variants: PlasmicWebsiteHeader__VariantsArgs;
  args: PlasmicWebsiteHeader__ArgsType;
  overrides: PlasmicWebsiteHeader__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"headerNavbar"}
      data-plasmic-override={overrides.headerNavbar}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.headerNavbar
      )}
    >
      <div
        data-plasmic-name={"navbarContainer"}
        data-plasmic-override={overrides.navbarContainer}
        className={classNames(projectcss.all, sty.navbarContainer)}
      >
        <PlasmicLink__
          data-plasmic-name={"homeButtonLink"}
          data-plasmic-override={overrides.homeButtonLink}
          className={classNames(
            projectcss.all,
            projectcss.a,
            sty.homeButtonLink
          )}
          component={Link}
          legacyBehavior={false}
          platform={"nextjs"}
        >
          <PlasmicImg__
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={"60px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"none"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"60px"}
            src={{
              src: "/plasmic/amir_ghahari_website/images/homeButtonSvgrepoComSvg.svg",
              fullWidth: 800,
              fullHeight: 800,
              aspectRatio: undefined
            }}
          />
        </PlasmicLink__>
        <div
          data-plasmic-name={"pagesLinksContainer"}
          data-plasmic-override={overrides.pagesLinksContainer}
          className={classNames(projectcss.all, sty.pagesLinksContainer)}
        >
          <PlasmicLink__
            data-plasmic-name={"aboutLink"}
            data-plasmic-override={overrides.aboutLink}
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.aboutLink
            )}
            component={Link}
            href={"https://www.plasmic.app/"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"About Me"}
          </PlasmicLink__>
          <PlasmicLink__
            data-plasmic-name={"skills"}
            data-plasmic-override={overrides.skills}
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.skills
            )}
            component={Link}
            href={"https://www.plasmic.app/"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Skills"}
          </PlasmicLink__>
          <PlasmicLink__
            data-plasmic-name={"resume"}
            data-plasmic-override={overrides.resume}
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.resume
            )}
            component={Link}
            href={"https://www.plasmic.app/"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Resume"}
          </PlasmicLink__>
          <PlasmicLink__
            data-plasmic-name={"projects"}
            data-plasmic-override={overrides.projects}
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.projects
            )}
            component={Link}
            href={"https://www.plasmic.app/"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Projects"}
          </PlasmicLink__>
          <PlasmicLink__
            data-plasmic-name={"contact"}
            data-plasmic-override={overrides.contact}
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.contact
            )}
            component={Link}
            href={"https://www.plasmic.app/"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Contact"}
          </PlasmicLink__>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  headerNavbar: [
    "headerNavbar",
    "navbarContainer",
    "homeButtonLink",
    "img",
    "pagesLinksContainer",
    "aboutLink",
    "skills",
    "resume",
    "projects",
    "contact"
  ],
  navbarContainer: [
    "navbarContainer",
    "homeButtonLink",
    "img",
    "pagesLinksContainer",
    "aboutLink",
    "skills",
    "resume",
    "projects",
    "contact"
  ],
  homeButtonLink: ["homeButtonLink", "img"],
  img: ["img"],
  pagesLinksContainer: [
    "pagesLinksContainer",
    "aboutLink",
    "skills",
    "resume",
    "projects",
    "contact"
  ],
  aboutLink: ["aboutLink"],
  skills: ["skills"],
  resume: ["resume"],
  projects: ["projects"],
  contact: ["contact"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  headerNavbar: "div";
  navbarContainer: "div";
  homeButtonLink: "a";
  img: typeof PlasmicImg__;
  pagesLinksContainer: "div";
  aboutLink: "a";
  skills: "a";
  resume: "a";
  projects: "a";
  contact: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicWebsiteHeader__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicWebsiteHeader__VariantsArgs;
    args?: PlasmicWebsiteHeader__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicWebsiteHeader__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicWebsiteHeader__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicWebsiteHeader__ArgProps,
          internalVariantPropNames: PlasmicWebsiteHeader__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicWebsiteHeader__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "headerNavbar") {
    func.displayName = "PlasmicWebsiteHeader";
  } else {
    func.displayName = `PlasmicWebsiteHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicWebsiteHeader = Object.assign(
  // Top-level PlasmicWebsiteHeader renders the root element
  makeNodeComponent("headerNavbar"),
  {
    // Helper components rendering sub-elements
    navbarContainer: makeNodeComponent("navbarContainer"),
    homeButtonLink: makeNodeComponent("homeButtonLink"),
    img: makeNodeComponent("img"),
    pagesLinksContainer: makeNodeComponent("pagesLinksContainer"),
    aboutLink: makeNodeComponent("aboutLink"),
    skills: makeNodeComponent("skills"),
    resume: makeNodeComponent("resume"),
    projects: makeNodeComponent("projects"),
    contact: makeNodeComponent("contact"),

    // Metadata about props expected for PlasmicWebsiteHeader
    internalVariantProps: PlasmicWebsiteHeader__VariantProps,
    internalArgProps: PlasmicWebsiteHeader__ArgProps
  }
);

export default PlasmicWebsiteHeader;
/* prettier-ignore-end */
