/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1MA8tVtTQ6ARhYAYML2fXH
// Component: MjSK7j5twT-j

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/styleTokensProvider
import { config } from "@/lib/config"; // MANUALLY ADDED: re-add after npx plasmic sync

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/projectcss
import sty from "./PlasmicHome.module.css"; // plasmic-import: MjSK7j5twT-j/css

import BrandLinkedinIcon from "./icons/PlasmicIcon__BrandLinkedin"; // plasmic-import: YL_7Hzz6ddJB/icon
import BrandGithubFilledIcon from "./icons/PlasmicIcon__BrandGithubFilled"; // plasmic-import: jgc3Mi7tL_Sx/icon
import BrandInstagramIcon from "./icons/PlasmicIcon__BrandInstagram"; // plasmic-import: sPs8xq4XDSB7/icon
import BrandFacebookFilledIcon from "./icons/PlasmicIcon__BrandFacebookFilled"; // plasmic-import: gYHB8kOr7qS6/icon
import ArrowNarrowRightIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__ArrowNarrowRight"; // plasmic-import: deFMwOdoPOwL/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q: any, $ctx: any) {
  return {
    title: "Home",

    openGraph: {
      title: "Home"
    },
    twitter: {
      card: "summary",
      title: "Home"
    }
  };
}

createPlasmicElementProxy;

export type PlasmicHome__VariantMembers = {};
export type PlasmicHome__VariantsArgs = {};
type VariantPropType = keyof PlasmicHome__VariantsArgs;
export const PlasmicHome__VariantProps = new Array<VariantPropType>();

export type PlasmicHome__ArgsType = {};
type ArgPropType = keyof PlasmicHome__ArgsType;
export const PlasmicHome__ArgProps = new Array<ArgPropType>();

export type PlasmicHome__OverridesType = {
  mainPage?: Flex__<"div">;
  socialMediaContainer?: Flex__<"div">;
  linkedinLink?: Flex__<"a"> & Partial<LinkProps>;
  githubLink?: Flex__<"a"> & Partial<LinkProps>;
  instagramLink?: Flex__<"a"> & Partial<LinkProps>;
  facebookLink?: Flex__<"a"> & Partial<LinkProps>;
  pagesLinksContainer?: Flex__<"div">;
  projects?: Flex__<"a"> & Partial<LinkProps>;
  aboutLink?: Flex__<"a"> & Partial<LinkProps>;
  skills?: Flex__<"a"> & Partial<LinkProps>;
  resume?: Flex__<"a"> & Partial<LinkProps>;
  contact2?: Flex__<"a"> & Partial<LinkProps>;
  contact?: Flex__<"a"> & Partial<LinkProps>;
};

export interface DefaultHomeProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHome__RenderFunc(props: {
  variants: PlasmicHome__VariantsArgs;
  args: PlasmicHome__ArgsType;
  overrides: PlasmicHome__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"mainPage"}
          data-plasmic-override={overrides.mainPage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.mainPage
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__pllGz)}>
            <div
              data-plasmic-name={"socialMediaContainer"}
              data-plasmic-override={overrides.socialMediaContainer}
              className={classNames(projectcss.all, sty.socialMediaContainer)}
            >
              <PlasmicLink__
                data-plasmic-name={"linkedinLink"}
                data-plasmic-override={overrides.linkedinLink}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.linkedinLink
                )}
                component={Link}
                href={config.linkedin}
                legacyBehavior={false}
                platform={"nextjs"}
                target={"_blank"}
              >
                <BrandLinkedinIcon
                  className={classNames(projectcss.all, sty.svg__hklGa)}
                  role={"img"}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"githubLink"}
                data-plasmic-override={overrides.githubLink}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.githubLink
                )}
                component={Link}
                href={config.github}
                legacyBehavior={false}
                platform={"nextjs"}
                target={"_blank"}
              >
                <BrandGithubFilledIcon
                  className={classNames(projectcss.all, sty.svg___9Xn7)}
                  role={"img"}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"instagramLink"}
                data-plasmic-override={overrides.instagramLink}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.instagramLink
                )}
                component={Link}
                href={config.instagram}
                legacyBehavior={false}
                platform={"nextjs"}
                target={"_blank"}
              >
                <BrandInstagramIcon
                  className={classNames(projectcss.all, sty.svg__o9DFh)}
                  role={"img"}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"facebookLink"}
                data-plasmic-override={overrides.facebookLink}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.facebookLink
                )}
                component={Link}
                href={config.facebook}
                legacyBehavior={false}
                platform={"nextjs"}
                target={"_blank"}
              >
                <BrandFacebookFilledIcon
                  className={classNames(projectcss.all, sty.svg__ohSb5)}
                  role={"img"}
                />
              </PlasmicLink__>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox___15HVv)}>
              <div className={classNames(projectcss.all, sty.freeBox__m2Nvo)}>
                <div
                  data-plasmic-name={"pagesLinksContainer"}
                  data-plasmic-override={overrides.pagesLinksContainer}
                  className={classNames(
                    projectcss.all,
                    sty.pagesLinksContainer
                  )}
                >
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__gexrx
                    )}
                    component={Link}
                    href={`/`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"HOME"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    data-plasmic-name={"projects"}
                    data-plasmic-override={overrides.projects}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.projects
                    )}
                    component={Link}
                    href={`/work-experience`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Work Experience"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    data-plasmic-name={"aboutLink"}
                    data-plasmic-override={overrides.aboutLink}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.aboutLink
                    )}
                    component={Link}
                    href={`/about-me`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"About Me"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    data-plasmic-name={"skills"}
                    data-plasmic-override={overrides.skills}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.skills
                    )}
                    component={Link}
                    href={`/skills`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Skills"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    data-plasmic-name={"resume"}
                    data-plasmic-override={overrides.resume}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.resume
                    )}
                    component={Link}
                    href={`/resume`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Resume"}
                  </PlasmicLink__>
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : false
                  ) ? (
                    <PlasmicLink__
                      data-plasmic-name={"contact2"}
                      data-plasmic-override={overrides.contact2}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.contact2
                      )}
                      component={Link}
                      href={"https://www.plasmic.app/"}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      {"Contact Me"}
                    </PlasmicLink__>
                  ) : null}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox__gdzFt)}
                />

                <PlasmicLink__
                  data-plasmic-name={"contact"}
                  data-plasmic-override={overrides.contact}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.contact
                  )}
                  component={Link}
                  href={`/contact`}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {"Contact Me"}
                </PlasmicLink__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___9Wku)}>
                <div className={classNames(projectcss.all, sty.freeBox__mXwEk)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__up1Wr)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__fUiIp)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___0PsZx
                        )}
                      >
                        {"HEY, I'M "}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hGjJf
                        )}
                      >
                        {"AmirHESAM Ghahari"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__elhc)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__okvsT
                        )}
                      >
                        {"But you can call me  "}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___0SKxC
                        )}
                      >
                        {"Amir"}
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tc2Cz
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "           I'm a Data Platform & Solutions Engineer             \n        & Cloud Data Architect            "
                      : "I'm a Data Platform & Solutions Engineer          \n& Cloud Data Architect       "}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___5Ly6Q)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__gFpdo)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__n0W7
                        )}
                      >
                        <PlasmicLink__
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            sty.link__b9Nku
                          )}
                          component={Link}
                          href={`/work-experience`}
                          legacyBehavior={false}
                          platform={"nextjs"}
                        >
                          <ArrowNarrowRightIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__ygcqp
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___9YxzI
                            )}
                          >
                            {"see my experience"}
                          </div>
                        </PlasmicLink__>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__iI64
                        )}
                      >
                        <PlasmicLink__
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            sty.link__fx6Ol
                          )}
                          component={Link}
                          href={`/about-me`}
                          legacyBehavior={false}
                          platform={"nextjs"}
                        >
                          <ArrowNarrowRightIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__l8VX
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__qrZv
                            )}
                          >
                            {"more about me"}
                          </div>
                        </PlasmicLink__>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___0Leu4
                        )}
                      >
                        <PlasmicLink__
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            sty.link__vxnhe
                          )}
                          component={Link}
                          href={`/resume`}
                          legacyBehavior={false}
                          platform={"nextjs"}
                        >
                          <ArrowNarrowRightIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__b6M4S
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gFTv5
                            )}
                          >
                            {"see my resume "}
                          </div>
                        </PlasmicLink__>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  mainPage: [
    "mainPage",
    "socialMediaContainer",
    "linkedinLink",
    "githubLink",
    "instagramLink",
    "facebookLink",
    "pagesLinksContainer",
    "projects",
    "aboutLink",
    "skills",
    "resume",
    "contact2",
    "contact"
  ],
  socialMediaContainer: [
    "socialMediaContainer",
    "linkedinLink",
    "githubLink",
    "instagramLink",
    "facebookLink"
  ],
  linkedinLink: ["linkedinLink"],
  githubLink: ["githubLink"],
  instagramLink: ["instagramLink"],
  facebookLink: ["facebookLink"],
  pagesLinksContainer: [
    "pagesLinksContainer",
    "projects",
    "aboutLink",
    "skills",
    "resume",
    "contact2"
  ],
  projects: ["projects"],
  aboutLink: ["aboutLink"],
  skills: ["skills"],
  resume: ["resume"],
  contact2: ["contact2"],
  contact: ["contact"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  mainPage: "div";
  socialMediaContainer: "div";
  linkedinLink: "a";
  githubLink: "a";
  instagramLink: "a";
  facebookLink: "a";
  pagesLinksContainer: "div";
  projects: "a";
  aboutLink: "a";
  skills: "a";
  resume: "a";
  contact2: "a";
  contact: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHome__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHome__VariantsArgs;
    args?: PlasmicHome__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHome__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHome__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHome__ArgProps,
          internalVariantPropNames: PlasmicHome__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "mainPage") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("mainPage"),
  {
    // Helper components rendering sub-elements
    socialMediaContainer: makeNodeComponent("socialMediaContainer"),
    linkedinLink: makeNodeComponent("linkedinLink"),
    githubLink: makeNodeComponent("githubLink"),
    instagramLink: makeNodeComponent("instagramLink"),
    facebookLink: makeNodeComponent("facebookLink"),
    pagesLinksContainer: makeNodeComponent("pagesLinksContainer"),
    projects: makeNodeComponent("projects"),
    aboutLink: makeNodeComponent("aboutLink"),
    skills: makeNodeComponent("skills"),
    resume: makeNodeComponent("resume"),
    contact2: makeNodeComponent("contact2"),
    contact: makeNodeComponent("contact"),

    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pagePath: "/",
      searchParams: {},
      params: {}
    })
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
