/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1MA8tVtTQ6ARhYAYML2fXH
// Component: 1x43ZLCplojR

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/styleTokensProvider
import { config } from "@/lib/config"; // MANUALLY ADDED: re-add after npx plasmic sync

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/projectcss
import sty from "./PlasmicAboutMe.module.css"; // plasmic-import: 1x43ZLCplojR/css

import CircleFilledIcon from "./icons/PlasmicIcon__CircleFilled"; // plasmic-import: MtO7pWUwIhVA/icon
import CodingHtmlSvgrepoComSvgIcon from "./icons/PlasmicIcon__CodingHtmlSvgrepoComSvg"; // plasmic-import: gOGEOMzO-5dH/icon
import DatabaseSvgrepoComSvgIcon from "./icons/PlasmicIcon__DatabaseSvgrepoComSvg"; // plasmic-import: f1KXDkDsDuA9/icon
import DataReportSvgrepoComSvgIcon from "./icons/PlasmicIcon__DataReportSvgrepoComSvg"; // plasmic-import: 8KquinGZmziR/icon
import AwsKinesisSvgrepoComSvgIcon from "./icons/PlasmicIcon__AwsKinesisSvgrepoComSvg"; // plasmic-import: x8sW9Otz0xvE/icon
import CloudComputingAiSvgrepoComSvgIcon from "./icons/PlasmicIcon__CloudComputingAiSvgrepoComSvg"; // plasmic-import: eZ85Bg5qyXqB/icon
import CloudDatabaseHostingSvgrepoComSvgIcon from "./icons/PlasmicIcon__CloudDatabaseHostingSvgrepoComSvg"; // plasmic-import: Bssew3GnfDVB/icon
import ComputeEngineSvgrepoComSvgIcon from "./icons/PlasmicIcon__ComputeEngineSvgrepoComSvg"; // plasmic-import: vYp4UoM46He0/icon
import CodingHtmlSvgrepoCom1SvgIcon from "./icons/PlasmicIcon__CodingHtmlSvgrepoCom1Svg"; // plasmic-import: MIHq_wYj0sQV/icon
import WebsiteQuestionSvgrepoComSvgIcon from "./icons/PlasmicIcon__WebsiteQuestionSvgrepoComSvg"; // plasmic-import: vWB2ywiSiYFT/icon
import BrandInstagramIcon from "./icons/PlasmicIcon__BrandInstagram"; // plasmic-import: sPs8xq4XDSB7/icon
import BrandFacebookFilledIcon from "./icons/PlasmicIcon__BrandFacebookFilled"; // plasmic-import: gYHB8kOr7qS6/icon
import BrandLinkedinIcon from "./icons/PlasmicIcon__BrandLinkedin"; // plasmic-import: YL_7Hzz6ddJB/icon
import BrandGithubFilledIcon from "./icons/PlasmicIcon__BrandGithubFilled"; // plasmic-import: jgc3Mi7tL_Sx/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q: any, $ctx: any) {
  return {
    title: "about-me",

    openGraph: {
      title: "about-me"
    },
    twitter: {
      card: "summary",
      title: "about-me"
    }
  };
}

createPlasmicElementProxy;

export type PlasmicAboutMe__VariantMembers = {};
export type PlasmicAboutMe__VariantsArgs = {};
type VariantPropType = keyof PlasmicAboutMe__VariantsArgs;
export const PlasmicAboutMe__VariantProps = new Array<VariantPropType>();

export type PlasmicAboutMe__ArgsType = {};
type ArgPropType = keyof PlasmicAboutMe__ArgsType;
export const PlasmicAboutMe__ArgProps = new Array<ArgPropType>();

export type PlasmicAboutMe__OverridesType = {
  mainPage?: Flex__<"div">;
  pagesLinksContainer?: Flex__<"div">;
  link?: Flex__<"a"> & Partial<LinkProps>;
  projects?: Flex__<"a"> & Partial<LinkProps>;
  aboutLink?: Flex__<"a"> & Partial<LinkProps>;
  skills?: Flex__<"a"> & Partial<LinkProps>;
  resume?: Flex__<"a"> & Partial<LinkProps>;
  contact?: Flex__<"a"> & Partial<LinkProps>;
  foreground?: Flex__<"div">;
  h2?: Flex__<"h2">;
  columns?: Flex__<"div">;
  socialMediaContainer?: Flex__<"div">;
  instagramLink?: Flex__<"a"> & Partial<LinkProps>;
  facebookLink?: Flex__<"a"> & Partial<LinkProps>;
  linkedinLink?: Flex__<"a"> & Partial<LinkProps>;
  githubLink?: Flex__<"a"> & Partial<LinkProps>;
};

export interface DefaultAboutMeProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAboutMe__RenderFunc(props: {
  variants: PlasmicAboutMe__VariantsArgs;
  args: PlasmicAboutMe__ArgsType;
  overrides: PlasmicAboutMe__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"mainPage"}
          data-plasmic-override={overrides.mainPage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.mainPage
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__gAKf6)}>
            <div
              data-plasmic-name={"pagesLinksContainer"}
              data-plasmic-override={overrides.pagesLinksContainer}
              className={classNames(projectcss.all, sty.pagesLinksContainer)}
            >
              <PlasmicLink__
                data-plasmic-name={"link"}
                data-plasmic-override={overrides.link}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link
                )}
                component={Link}
                href={`/`}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"HOME"}
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"projects"}
                data-plasmic-override={overrides.projects}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.projects
                )}
                component={Link}
                href={`/work-experience`}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"Work Experience"}
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"aboutLink"}
                data-plasmic-override={overrides.aboutLink}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.aboutLink
                )}
                component={Link}
                href={`/about-me`}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"About Me"}
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"skills"}
                data-plasmic-override={overrides.skills}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.skills
                )}
                component={Link}
                href={`/skills`}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"Skills"}
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"resume"}
                data-plasmic-override={overrides.resume}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.resume
                )}
                component={Link}
                href={`/resume`}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"Resume"}
              </PlasmicLink__>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__xRspv)} />

            <PlasmicLink__
              data-plasmic-name={"contact"}
              data-plasmic-override={overrides.contact}
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.contact
              )}
              component={Link}
              href={`/contact`}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Contact Me"}
            </PlasmicLink__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__sMsUa)}>
            <div className={classNames(projectcss.all, sty.freeBox__bvOrw)}>
              <div className={classNames(projectcss.all, sty.freeBox___36LsJ)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___9972W)}
                  displayHeight={"450px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/amir_ghahari_website/images/img7130Jpg.jpg",
                    fullWidth: 3024,
                    fullHeight: 4032,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___4BjEk)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nIbvX
                  )}
                >
                  {`I'm ${config.name}`}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qsJi
                  )}
                >
                  {"Data Platform Engineer"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xbNwy
                  )}
                >
                  {"Data Solutions Engineer"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jQlRr
                  )}
                >
                  {"Cloud Data Architect"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pmE
                  )}
                >
                  {
                    "I am a senior data platform and solutions engineer and cloud architect with extensive experience designing and building modern, cloud-native data platforms across healthcare, research, and analytics environments. Double certified as AWS Solutions Architect and Data Engineering Professional, I specialize in creating scalable batch and real-time pipelines that transform complex data into reliable, actionable insights for business and analytics teams."
                  }
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__e56Rz)}>
            <div className={classNames(projectcss.all, sty.freeBox__ucBn9)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__dVueR)}
                displayHeight={"200px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"95%"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/amir_ghahari_website/images/_7240514Jpg.jpg",
                  fullWidth: 3000,
                  fullHeight: 2000,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__lTiv5
                )}
              >
                {"Education"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__slYHn
                )}
              >
                {"Master of Science in Systems Engineering (MSc)"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jtHo
                )}
              >
                {"Bachelor of Science in Computer Science (BSc)"}
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__kMsds)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__zo3Xg)}
                displayHeight={"200px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"95%"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/amir_ghahari_website/images/_7090038Jpg.jpg",
                  fullWidth: 3000,
                  fullHeight: 2000,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hkr4F
                )}
              >
                {"Certificates"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__kErV
                )}
              >
                {"AWS Certified Solutions Architect \u2013 Associate"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mRyQj
                )}
              >
                {"AWS Certified Data Engineer \u2013 Associate"}
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__t3Zqb)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__weU7D)}
                displayHeight={"200px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"95%"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/amir_ghahari_website/images/_20945551Jpg.jpg",
                  fullWidth: 5157,
                  fullHeight: 3438,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__znb6S
                )}
              >
                {"Professional Experience"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__scWai
                )}
              >
                {"7 Yeard of Professional Work Experience"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uvBd
                )}
              >
                {"+40 Completed Professional Technical Projects"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__l0Dmd
                )}
              >
                {"3 Reputable Companies & many Private Clients"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__rjCZf)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__rFtdm
              )}
            >
              {"More About me"}
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__n4Kx4)}>
              <div className={classNames(projectcss.all, sty.freeBox__tK2I)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__naNM)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/amir_ghahari_website/images/businessOfficeRemoteLifestyleJpg.jpg",
                    fullWidth: 3840,
                    fullHeight: 5120,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___8Jg3)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wZ4J6
                  )}
                >
                  {
                    "I am an experienced senior data engineer and data developer with a strong track record of designing, building, and optimizing large-scale, cloud-native data platforms and pipelines. With over seven years of professional experience across healthcare, research, and analytics environments, I have consistently delivered reliable, high-performance data systems that enable organizations to make informed, data-driven decisions.\n\nThroughout my career, I have worked as a critical bridge between backend engineering teams that generate large volumes of data and business, analytics, and operations teams that rely on accurate, timely insights. This position at the center of data flow has allowed me to develop a deep understanding of both technical constraints and business priorities, ensuring that data solutions are not only technically sound but also strategically valuable.\n\nMy role often sits at the intersection of technology, data, and business. I collaborate closely with application developers to understand system architectures, data sources, and event flows, while working with analysts, researchers, and stakeholders to define reporting, modeling, and performance requirements. This dual perspective enables me to translate complex business needs into scalable, maintainable technical solutions that evolve with organizational growth.\n"
                  }
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__hsDzg)}>
              <div className={classNames(projectcss.all, sty.freeBox__czQz3)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__eiEv6)}
                  displayHeight={"194px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"85%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/amir_ghahari_website/images/_2305I602014FM009C7GatheringDataSearchingFlatCompositionJpg.jpg",
                    fullWidth: 6397,
                    fullHeight: 2345,
                    aspectRatio: undefined
                  }}
                />

                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__aoMsl
                  )}
                >
                  {"Core Expertise and Focus Areas"}
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lp06R
                  )}
                >
                  {
                    "I specialize in building end-to-end data ecosystems that support data enablement, operational reporting, advanced analytics, and machine learning initiatives, including:"
                  }
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__eoYek)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___5Et8K)}
                  >
                    <CircleFilledIcon
                      className={classNames(projectcss.all, sty.svg___3DUil)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___4IC4O
                      )}
                    >
                      {
                        "Designing centralized data lakes and data warehouses that serve as single sources of truth"
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__vhE5)}
                  >
                    <CircleFilledIcon
                      className={classNames(projectcss.all, sty.svg__rkUmU)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vkcSl
                      )}
                    >
                      {
                        "Developing batch and real-time integrations across distributed and event-driven systems"
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___2Cvop)}
                  >
                    <CircleFilledIcon
                      className={classNames(projectcss.all, sty.svg__ye3E9)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__e3Ssk
                      )}
                    >
                      {
                        "Implementing layered data models using dimensional and star schema best practices"
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__g8WY)}
                  >
                    <CircleFilledIcon
                      className={classNames(projectcss.all, sty.svg__dv92R)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__o5Ymd
                      )}
                    >
                      {
                        "Creating APIs and serverless services for real-time data ingestion and processing"
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__tcAsu)}
                  >
                    <CircleFilledIcon
                      className={classNames(projectcss.all, sty.svg__nVXzq)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rEJoo
                      )}
                    >
                      {
                        "Building robust ETL and ELT pipelines for enterprise, research, and analytical use cases"
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__hH9Bc)}
                  >
                    <CircleFilledIcon
                      className={classNames(projectcss.all, sty.svg__aSNw)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uzT15
                      )}
                    >
                      {
                        "Establishing data governance, quality, and monitoring frameworks"
                      }
                    </div>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__lkgxj)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__raqJz)}
                  displayHeight={"194px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/amir_ghahari_website/images/_2301Q891008PM004C20SmartIndustryIndustrial40FlatLineSetJpg.jpg",
                    fullWidth: 6834,
                    fullHeight: 3001,
                    aspectRatio: undefined
                  }}
                />

                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__tTkmS
                  )}
                >
                  {"Projects and Impact"}
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ilAp5
                  )}
                >
                  {
                    "Over the years, I have led and contributed to multiple high-impact projects, including:"
                  }
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___1UiLb)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox___0N0C)}
                  >
                    <CircleFilledIcon
                      className={classNames(projectcss.all, sty.svg__pAgZn)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wa8Bc
                      )}
                    >
                      {
                        "Enterprise healthcare analytics platforms integrating batch and streaming pipelines"
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ff8Mf)}
                  >
                    <CircleFilledIcon
                      className={classNames(projectcss.all, sty.svg__n2I7E)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___5J4PF
                      )}
                    >
                      {
                        "Real-time ETL modernization frameworks using serverless and event-driven architectures"
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___9GDpn)}
                  >
                    <CircleFilledIcon
                      className={classNames(projectcss.all, sty.svg__rkXb)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ho3Dp
                      )}
                    >
                      {
                        "Political and social research data infrastructures supporting large-scale analytics"
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__upXno)}
                  >
                    <CircleFilledIcon
                      className={classNames(projectcss.all, sty.svg__c5Hvd)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__acq6A
                      )}
                    >
                      {
                        "Climate and health decision-support systems combining predictive modeling and visualization"
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__dCVyg)}
                  >
                    <CircleFilledIcon
                      className={classNames(projectcss.all, sty.svg__i1DPn)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xiDZh
                      )}
                    >
                      {
                        "Personal cloud-based laboratories for prototyping and experimentation"
                      }
                    </div>
                  </div>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wvppn
                  )}
                >
                  {
                    "These projects have helped organizations improve reporting speed, strengthen governance, reduce operational overhead, and unlock new analytical capabilities."
                  }
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___2V9Oe)}>
            <div className={classNames(projectcss.all, sty.freeBox__tUjR4)}>
              <div
                data-plasmic-name={"foreground"}
                data-plasmic-override={overrides.foreground}
                className={classNames(projectcss.all, sty.foreground)}
              >
                <h2
                  data-plasmic-name={"h2"}
                  data-plasmic-override={overrides.h2}
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2
                  )}
                >
                  {"Technical Skills and Stack"}
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1LclT
                  )}
                >
                  {
                    "To deliver reliable, scalable, and high-performance data solutions, I leverage a broad and modern technical skill set across software engineering, data engineering, cloud architecture, and analytics. My technical expertise enables me to design secure, scalable, and cost-effective data platforms that support analytics, reporting, and advanced data science initiatives."
                  }
                </div>
              </div>
              <div
                data-plasmic-name={"columns"}
                data-plasmic-override={overrides.columns}
                className={classNames(projectcss.all, sty.columns)}
              >
                <div className={classNames(projectcss.all, sty.column__t1Avu)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__huUu6)}
                  >
                    <CodingHtmlSvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg___7E5Hh)}
                      role={"img"}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__l5Pb)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__h5B7
                        )}
                      >
                        {"Programming & Version Control"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__a1Ojt
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__pSmCw
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__x88Qo
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__uz08
                            )}
                          >
                            {"Python"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__mdfGl
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__vNRtX
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__rjr5O
                            )}
                          >
                            {"Ruby"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__c424H
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__v4YOm
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__d11Xe
                            )}
                          >
                            {"JavaScript"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___8Lrx7
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__zyXof
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ewFv7
                            )}
                          >
                            {"Git & GitHub"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__hiznI
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___8UgNo
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__cPyxj
                            )}
                          >
                            {"Jenkins"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__winJ6
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__oAcl5
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__szEy9
                            )}
                          >
                            {"Docker & CI/CD workflows"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__kLzfS)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__fmUl)}
                  >
                    <DatabaseSvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg___6Kewx)}
                      role={"img"}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__phzez)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zyFnl
                        )}
                      >
                        {"Data & Query Technologies"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__fnUMj
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__tqodT
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__zmDgA
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__k8Ig
                            )}
                          >
                            {"SQL"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__jpfh6
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__rBpNa
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__fGto9
                            )}
                          >
                            {"DBT"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___201X
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__bMn5H
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__wvaX4
                            )}
                          >
                            {"Apache Spark"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__dvm4T
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__uuuC
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__g65XB
                            )}
                          >
                            {"Apache Airflow"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__uqeTx
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__oJjeE
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__xgdTg
                            )}
                          >
                            {"Data modeling (dimensional and star schemas)"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__ux0Rt)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___5BQpx)}
                  >
                    <DataReportSvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg__r0BZa)}
                      role={"img"}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__gqJe1)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__oieV7
                        )}
                      >
                        {"Business Intelligence & Analytics"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__exqSu
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__t17U
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__oiKi0
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__nfA1K
                            )}
                          >
                            {"Tableau"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__k9Y01
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__ehOoY
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__upz1N
                            )}
                          >
                            {"Metabase"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___0EYqx
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__k4QEm
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__sx2RZ
                            )}
                          >
                            {"Amazon QuickSight"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__xzMn
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__sdbZz
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__bt9Xd
                            )}
                          >
                            {"Power BI"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__i9YQ1
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__c3Ref
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__bh06D
                            )}
                          >
                            {"Dashboard design and KPI development"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__zg47T)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__cnCxr)}
                  >
                    <AwsKinesisSvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg__ibYf)}
                      role={"img"}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__gKay)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__d0SJr
                        )}
                      >
                        {"Real-Time & Streaming Systems"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___8M7R
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__l9LZd
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__sACsZ
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__oowyq
                            )}
                          >
                            {"Apache Kafka"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__vjzbz
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__divfw
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__zjw83
                            )}
                          >
                            {"AWS Kinesis Firehose"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__p3XG
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__znyO
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___7ROp
                            )}
                          >
                            {"AWS Kinesis Data Streams"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__x419D
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__r38D5
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__oQh3X
                            )}
                          >
                            {"Event-driven architectures"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__uncoe)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__kdPBi)}
                  >
                    <CloudComputingAiSvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg__k5GdT)}
                      role={"img"}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__nyWlj)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__exVd
                        )}
                      >
                        {"Machine Learning & AI"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__vck27
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ctf0M
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__x7T5U
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ojlTs
                            )}
                          >
                            {"AWS SageMaker"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__iC2UP
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__aogAi
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__qwgXs
                            )}
                          >
                            {"AWS Rekognition"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__gyaJb
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__t67Xt
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__p6SZh
                            )}
                          >
                            {"Scikit-learn"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__wo7X2
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__eqYw
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__dc82U
                            )}
                          >
                            {"Model integration with data pipelines"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__v0ZTm)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___11Gm5)}
                  >
                    <CloudDatabaseHostingSvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg___4YIzf)}
                      role={"img"}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__eE4U1)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__sOhkc
                        )}
                      >
                        {"AWS Databases & Storage"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___92UfV
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ergmg
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__fkrdG
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__cQ8Jv
                            )}
                          >
                            {"AWS S3"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__opLff
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__rc6Xz
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___8CZe
                            )}
                          >
                            {"Redshift"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__p4KD
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___6SjRz
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__iLKk
                            )}
                          >
                            {"DynamoDB"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__xrSne
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__ojJfp
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__yqlep
                            )}
                          >
                            {"RDS & Aurora"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__d0FOy
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__tvofb
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__wjB5O
                            )}
                          >
                            {"Data lake and warehouse design"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__gwgTi)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___5WkrX)}
                  >
                    <ComputeEngineSvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg__er97H)}
                      role={"img"}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__mV8Pa)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___9N4M
                        )}
                      >
                        {"AWS Compute & Infrastructure"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__q8Lbs
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__cG7U
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__hwR11
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__iTh1
                            )}
                          >
                            {"AWS Lambda"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__s6GL
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___6R8UG
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__aupDu
                            )}
                          >
                            {"AWS EC2"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___6CwN4
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__brw9H
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__dLZb
                            )}
                          >
                            {"AWS ECS"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__avbsj
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__xopUx
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__wRup
                            )}
                          >
                            {"Elastic Load Balancer"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__wvAZh
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__bjS2
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__zdW7W
                            )}
                          >
                            {"Serverless and containerized systems"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__hAyhU)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__dh6Vg)}
                  >
                    <CodingHtmlSvgrepoCom1SvgIcon
                      className={classNames(projectcss.all, sty.svg__jpAl5)}
                      role={"img"}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__rfdu1)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__oxhQc
                        )}
                      >
                        {"AWS Data Engineering Services"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___7CaI1
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__vBoOw
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__lbauK
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__lMcFv
                            )}
                          >
                            {"AWS Glue"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__pbg0E
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__cmJFp
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__qKoao
                            )}
                          >
                            {"AWS DMS"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__yBtpZ
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___23Qo9
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__hQfAr
                            )}
                          >
                            {"Amazon OpenSearch"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__aiRmR
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__x36LU
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gWkbQ
                            )}
                          >
                            {"Lake Formation"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__rgLbJ
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__atWs
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__pBdEx
                            )}
                          >
                            {"Data governance and cataloging"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__kwpK)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___1Qy1U)}
                  >
                    <WebsiteQuestionSvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg__lVNj)}
                      role={"img"}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__wbncf)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nKyZ
                        )}
                      >
                        {"Web & Integration Services"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__au0J
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__r545V
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__dmwF2
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__t8Ii1
                            )}
                          >
                            {"AWS API Gateway"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__x2Grv
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__gzTkt
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__bKeG
                            )}
                          >
                            {"AWS CloudFront"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__uQn29
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__zYuv9
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__uOIc
                            )}
                          >
                            {"Route 53"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___7UTqh
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__bJWyh
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ptCUw
                            )}
                          >
                            {"SQS, SNS, EventBridge"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__aE37T
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__cR0X
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__cu1Ob
                            )}
                          >
                            {"AWS VPC"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ddKXk
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__nnE8Q
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__mBaE2
                            )}
                          >
                            {"AWS CloudFormation"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__veX8)}>
            <div
              data-plasmic-name={"socialMediaContainer"}
              data-plasmic-override={overrides.socialMediaContainer}
              className={classNames(projectcss.all, sty.socialMediaContainer)}
            >
              <PlasmicLink__
                data-plasmic-name={"instagramLink"}
                data-plasmic-override={overrides.instagramLink}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.instagramLink
                )}
                component={Link}
                href={config.instagram}
                legacyBehavior={false}
                platform={"nextjs"}
                target={"_blank"}
              >
                <BrandInstagramIcon
                  className={classNames(projectcss.all, sty.svg__ru4Sx)}
                  role={"img"}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"facebookLink"}
                data-plasmic-override={overrides.facebookLink}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.facebookLink
                )}
                component={Link}
                href={config.facebook}
                legacyBehavior={false}
                platform={"nextjs"}
                target={"_blank"}
              >
                <BrandFacebookFilledIcon
                  className={classNames(projectcss.all, sty.svg__jjfV9)}
                  role={"img"}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"linkedinLink"}
                data-plasmic-override={overrides.linkedinLink}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.linkedinLink
                )}
                component={Link}
                href={config.linkedin}
                legacyBehavior={false}
                platform={"nextjs"}
                target={"_blank"}
              >
                <BrandLinkedinIcon
                  className={classNames(projectcss.all, sty.svg___8Zv9P)}
                  role={"img"}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"githubLink"}
                data-plasmic-override={overrides.githubLink}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.githubLink
                )}
                component={Link}
                href={config.github}
                legacyBehavior={false}
                platform={"nextjs"}
                target={"_blank"}
              >
                <BrandGithubFilledIcon
                  className={classNames(projectcss.all, sty.svg___425DQ)}
                  role={"img"}
                />
              </PlasmicLink__>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  mainPage: [
    "mainPage",
    "pagesLinksContainer",
    "link",
    "projects",
    "aboutLink",
    "skills",
    "resume",
    "contact",
    "foreground",
    "h2",
    "columns",
    "socialMediaContainer",
    "instagramLink",
    "facebookLink",
    "linkedinLink",
    "githubLink"
  ],
  pagesLinksContainer: [
    "pagesLinksContainer",
    "link",
    "projects",
    "aboutLink",
    "skills",
    "resume"
  ],
  link: ["link"],
  projects: ["projects"],
  aboutLink: ["aboutLink"],
  skills: ["skills"],
  resume: ["resume"],
  contact: ["contact"],
  foreground: ["foreground", "h2"],
  h2: ["h2"],
  columns: ["columns"],
  socialMediaContainer: [
    "socialMediaContainer",
    "instagramLink",
    "facebookLink",
    "linkedinLink",
    "githubLink"
  ],
  instagramLink: ["instagramLink"],
  facebookLink: ["facebookLink"],
  linkedinLink: ["linkedinLink"],
  githubLink: ["githubLink"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  mainPage: "div";
  pagesLinksContainer: "div";
  link: "a";
  projects: "a";
  aboutLink: "a";
  skills: "a";
  resume: "a";
  contact: "a";
  foreground: "div";
  h2: "h2";
  columns: "div";
  socialMediaContainer: "div";
  instagramLink: "a";
  facebookLink: "a";
  linkedinLink: "a";
  githubLink: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAboutMe__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAboutMe__VariantsArgs;
    args?: PlasmicAboutMe__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicAboutMe__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicAboutMe__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAboutMe__ArgProps,
          internalVariantPropNames: PlasmicAboutMe__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAboutMe__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "mainPage") {
    func.displayName = "PlasmicAboutMe";
  } else {
    func.displayName = `PlasmicAboutMe.${nodeName}`;
  }
  return func;
}

export const PlasmicAboutMe = Object.assign(
  // Top-level PlasmicAboutMe renders the root element
  makeNodeComponent("mainPage"),
  {
    // Helper components rendering sub-elements
    pagesLinksContainer: makeNodeComponent("pagesLinksContainer"),
    link: makeNodeComponent("link"),
    projects: makeNodeComponent("projects"),
    aboutLink: makeNodeComponent("aboutLink"),
    skills: makeNodeComponent("skills"),
    resume: makeNodeComponent("resume"),
    contact: makeNodeComponent("contact"),
    foreground: makeNodeComponent("foreground"),
    h2: makeNodeComponent("h2"),
    columns: makeNodeComponent("columns"),
    socialMediaContainer: makeNodeComponent("socialMediaContainer"),
    instagramLink: makeNodeComponent("instagramLink"),
    facebookLink: makeNodeComponent("facebookLink"),
    linkedinLink: makeNodeComponent("linkedinLink"),
    githubLink: makeNodeComponent("githubLink"),

    // Metadata about props expected for PlasmicAboutMe
    internalVariantProps: PlasmicAboutMe__VariantProps,
    internalArgProps: PlasmicAboutMe__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pagePath: "/about-me",
      searchParams: {},
      params: {}
    })
  }
);

export default PlasmicAboutMe;
/* prettier-ignore-end */
