/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1MA8tVtTQ6ARhYAYML2fXH
// Component: L8xxuRK9jtE5

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/styleTokensProvider
import { config } from "@/lib/config"; // MANUALLY ADDED: re-add after npx plasmic sync

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/projectcss
import sty from "./PlasmicResume.module.css"; // plasmic-import: L8xxuRK9jtE5/css

import FileDownloadIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__FileDownload"; // plasmic-import: hGJakEfBLuHS/icon
import PhoneFilledIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__PhoneFilled"; // plasmic-import: hzGroelrxipC/icon
import MailFilledIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__MailFilled"; // plasmic-import: 5O_NkyWWmaDu/icon
import BrandLinkedinIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__BrandLinkedin"; // plasmic-import: KshNwg5oK9bk/icon
import LocationFilledIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__LocationFilled"; // plasmic-import: kNV7iKTCtrle/icon
import CalendarFilledIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__CalendarFilled"; // plasmic-import: mb8DIGQiQyid/icon
import CircleFilledIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__CircleFilled"; // plasmic-import: Z45_TKGL7Jxg/icon
import BrandInstagramIcon from "./icons/PlasmicIcon__BrandInstagram"; // plasmic-import: sPs8xq4XDSB7/icon
import BrandFacebookFilledIcon from "./icons/PlasmicIcon__BrandFacebookFilled"; // plasmic-import: gYHB8kOr7qS6/icon
import BrandLinkedinIcon2 from "./icons/PlasmicIcon__BrandLinkedin"; // plasmic-import: YL_7Hzz6ddJB/icon
import BrandGithubFilledIcon from "./icons/PlasmicIcon__BrandGithubFilled"; // plasmic-import: jgc3Mi7tL_Sx/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q: any, $ctx: any) {
  return {
    title: "Resume",

    openGraph: {
      title: "Resume"
    },
    twitter: {
      card: "summary",
      title: "Resume"
    }
  };
}

createPlasmicElementProxy;

export type PlasmicResume__VariantMembers = {};
export type PlasmicResume__VariantsArgs = {};
type VariantPropType = keyof PlasmicResume__VariantsArgs;
export const PlasmicResume__VariantProps = new Array<VariantPropType>();

export type PlasmicResume__ArgsType = {};
type ArgPropType = keyof PlasmicResume__ArgsType;
export const PlasmicResume__ArgProps = new Array<ArgPropType>();

export type PlasmicResume__OverridesType = {
  mainPage?: Flex__<"div">;
  pagesLinksContainer?: Flex__<"div">;
  link?: Flex__<"a"> & Partial<LinkProps>;
  projects?: Flex__<"a"> & Partial<LinkProps>;
  aboutLink?: Flex__<"a"> & Partial<LinkProps>;
  skills?: Flex__<"a"> & Partial<LinkProps>;
  resume?: Flex__<"a"> & Partial<LinkProps>;
  contact?: Flex__<"a"> & Partial<LinkProps>;
  socialMediaContainer?: Flex__<"div">;
  instagramLink?: Flex__<"a"> & Partial<LinkProps>;
  facebookLink?: Flex__<"a"> & Partial<LinkProps>;
  linkedinLink?: Flex__<"a"> & Partial<LinkProps>;
  githubLink?: Flex__<"a"> & Partial<LinkProps>;
};

export interface DefaultResumeProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicResume__RenderFunc(props: {
  variants: PlasmicResume__VariantsArgs;
  args: PlasmicResume__ArgsType;
  overrides: PlasmicResume__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const $globalActions = useGlobalActions?.();

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"mainPage"}
          data-plasmic-override={overrides.mainPage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.mainPage
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__fPbBl)}>
            <div
              data-plasmic-name={"pagesLinksContainer"}
              data-plasmic-override={overrides.pagesLinksContainer}
              className={classNames(projectcss.all, sty.pagesLinksContainer)}
            >
              <PlasmicLink__
                data-plasmic-name={"link"}
                data-plasmic-override={overrides.link}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link
                )}
                component={Link}
                href={`/`}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"HOME"}
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"projects"}
                data-plasmic-override={overrides.projects}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.projects
                )}
                component={Link}
                href={`/work-experience`}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"Work Experience"}
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"aboutLink"}
                data-plasmic-override={overrides.aboutLink}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.aboutLink
                )}
                component={Link}
                href={`/about-me`}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"About Me"}
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"skills"}
                data-plasmic-override={overrides.skills}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.skills
                )}
                component={Link}
                href={`/skills`}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"Skills"}
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"resume"}
                data-plasmic-override={overrides.resume}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.resume
                )}
                component={Link}
                href={`/resume`}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"Resume"}
              </PlasmicLink__>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__biAue)} />

            <PlasmicLink__
              data-plasmic-name={"contact"}
              data-plasmic-override={overrides.contact}
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.contact
              )}
              component={Link}
              href={`/contact`}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Contact Me"}
            </PlasmicLink__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__n0OBm)}>
            <button
              className={classNames(
                projectcss.all,
                projectcss.button,
                sty.button__cVx4N
              )}
              onClick={async event => {
                const $steps = {};

                $steps["goToHttpsAmirGhahariDevResumeAmirhesamGhahariCvPdf"] =
                  true
                    ? (() => {
                        const actionArgs = {
                          destination:
                            config.resumePdfUrl
                        };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                if (
                  $steps[
                    "goToHttpsAmirGhahariDevResumeAmirhesamGhahariCvPdf"
                  ] != null &&
                  typeof $steps[
                    "goToHttpsAmirGhahariDevResumeAmirhesamGhahariCvPdf"
                  ] === "object" &&
                  typeof $steps[
                    "goToHttpsAmirGhahariDevResumeAmirhesamGhahariCvPdf"
                  ].then === "function"
                ) {
                  $steps["goToHttpsAmirGhahariDevResumeAmirhesamGhahariCvPdf"] =
                    await $steps[
                      "goToHttpsAmirGhahariDevResumeAmirhesamGhahariCvPdf"
                    ];
                }

                $steps["invokeGlobalAction"] = true
                  ? (() => {
                      const actionArgs = {
                        args: [undefined, "Downloaded", undefined, 3, "top"]
                      };
                      return $globalActions[
                        "plasmic-antd5-config-provider.showNotification"
                      ]?.apply(null, [...actionArgs.args]);
                    })()
                  : undefined;
                if (
                  $steps["invokeGlobalAction"] != null &&
                  typeof $steps["invokeGlobalAction"] === "object" &&
                  typeof $steps["invokeGlobalAction"].then === "function"
                ) {
                  $steps["invokeGlobalAction"] =
                    await $steps["invokeGlobalAction"];
                }
              }}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__kcUks
                )}
              >
                {"Download CV"}
              </div>
              <FileDownloadIcon
                className={classNames(projectcss.all, sty.svg__a6Kg)}
                role={"img"}
              />
            </button>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__r7Ror)}>
            <div className={classNames(projectcss.all, sty.freeBox__iw6Ee)}>
              <div className={classNames(projectcss.all, sty.freeBox__ilwh8)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4CzqS
                  )}
                >
                  {config.fullName}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__b9I7F)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___5Qhac
                  )}
                >
                  {config.jobTitle}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__foHl5)}>
                <div className={classNames(projectcss.all, sty.freeBox__gQ4O3)}>
                  <PhoneFilledIcon
                    className={classNames(projectcss.all, sty.svg___0J9Li)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__v3Jbd
                    )}
                  >
                    {config.phone}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__f06YC)}>
                  <MailFilledIcon
                    className={classNames(projectcss.all, sty.svg__mfxzN)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tNeao
                    )}
                  >
                    {config.email}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox___6VZi)}>
                  <BrandLinkedinIcon
                    className={classNames(projectcss.all, sty.svg___3RMls)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xyHuK
                    )}
                  >
                    {config.linkedin}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__bqt6O)}>
                  <LocationFilledIcon
                    className={classNames(projectcss.all, sty.svg__oabcc)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__foYhl
                    )}
                  >
                    {"Toronto, Canada"}
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__knqva)}>
                <div className={classNames(projectcss.all, sty.freeBox__tan2N)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rGcs3
                    )}
                  >
                    {"Work History"}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__r4SoO)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zAmr
                      )}
                    >
                      {"Senior Data Engineer"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__bXwrH)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__q1V0N
                        )}
                      >
                        {"TELUS Health"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__lyajF
                        )}
                      >
                        <CalendarFilledIcon
                          className={classNames(projectcss.all, sty.svg__hFtgl)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___8M7R8
                          )}
                        >
                          {"04/2022 - Present"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__mYcov
                        )}
                      >
                        <LocationFilledIcon
                          className={classNames(projectcss.all, sty.svg__mvcP)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zlcGw
                          )}
                        >
                          {"Toronto, Canada"}
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__moX5
                      )}
                    >
                      {
                        "Spearheaded the design, implementation, maintenance, and optimization of cloud-native data pipelines, significantly improving data accuracy, latency and workflow e\ufb03ciency."
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__vunKq)}
                    >
                      <CircleFilledIcon
                        className={classNames(projectcss.all, sty.svg__os85B)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__altCh
                        )}
                      >
                        {
                          "Architected scalable data models using DBT, Python and Airflow implementing dimensional and star schema best practices, enhancing data accessibility for analytics and reporting teams by 50%"
                        }
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___1Gx8V
                      )}
                    >
                      <CircleFilledIcon
                        className={classNames(projectcss.all, sty.svg__bdpIc)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jaA3M
                        )}
                      >
                        {
                          "Employed Git workflows, Docker and Kubernetes to automate ETL processes, reducing manual intervention and improving overall system reliability"
                        }
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__h1IMk)}
                    >
                      <CircleFilledIcon
                        className={classNames(projectcss.all, sty.svg___0U4Kd)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pwKvy
                        )}
                      >
                        {
                          "Revamped legacy ETL systems, deploying real-time data processing frameworks via AWS DMS, Kinesis, and Lambda, increasing data processing e\ufb03ciency and reducing data latency by 80%"
                        }
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__x1HRp)}
                    >
                      <CircleFilledIcon
                        className={classNames(projectcss.all, sty.svg__s7QCs)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yvzDo
                        )}
                      >
                        {
                          "Established multi-layered data architectures using AWS Lambda, Athena, RDS and Glue, resulting in 40% faster analytics reporting and improving data governance compliance"
                        }
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__wXvZv)}
                    >
                      <CircleFilledIcon
                        className={classNames(projectcss.all, sty.svg__c70J1)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__p9OqL
                        )}
                      >
                        {
                          "Developed optimized SQL queries that improved reporting e\ufb03ciency across multiple business intelligence tools such as PowerBI and Tableau, enabling data-driven decisions and reducing query execution times by 20%"
                        }
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__qKay4)}
                    >
                      <CircleFilledIcon
                        className={classNames(projectcss.all, sty.svg___7U4Pz)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__y1Pef
                        )}
                      >
                        {
                          "Collaborated across teams to implement innovative solutions, improving operational e\ufb03ciency, focusing on problem solving attitude, performing code reviews and resolving data integrity issues with creative solution."
                        }
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__e5Iu)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___4Fbnh
                      )}
                    >
                      {"Data Engineer"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__cYrYd)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__j9L8N
                        )}
                      >
                        {"Data Sciences Inc."}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__rjQs
                        )}
                      >
                        <CalendarFilledIcon
                          className={classNames(projectcss.all, sty.svg__jaeK)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ruItq
                          )}
                        >
                          {"12/2020 - 04/2022"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__flsif
                        )}
                      >
                        <LocationFilledIcon
                          className={classNames(projectcss.all, sty.svg__luTMt)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__sA6H8
                          )}
                        >
                          {"Toronto, Canada"}
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nzm9X
                      )}
                    >
                      {
                        "Developed and refined advanced data pipelines, ensuring data accuracy for high-profile projects with the Liberal Party of Canada and Ontario Liberal Party."
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__jcEzI)}
                    >
                      <CircleFilledIcon
                        className={classNames(projectcss.all, sty.svg__yg25R)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__aq4Oe
                        )}
                      >
                        {
                          "Exploited SQL, NoSQL databases to process datasets in data warehouse, and\nimprove cleaning and processing times by 30% while ensuring compliance\nwith data governance policies"
                        }
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__fygC)}
                    >
                      <CircleFilledIcon
                        className={classNames(projectcss.all, sty.svg__tnse)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__dvWbx
                        )}
                      >
                        {
                          "Systematized workflows using custom Python scripts, reducing manual e\ufb00ort by 40% and accelerating data migration processes"
                        }
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__t5J9Q)}
                    >
                      <CircleFilledIcon
                        className={classNames(projectcss.all, sty.svg__oKh0G)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__sik1S
                        )}
                      >
                        {
                          "Designed and implemented cloud-based pipelines with AWS services such as Lambda, Redshift, Step Function and EventBridge, achieving cost e\ufb03ciency and reducing deployment times"
                        }
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ynkOs)}
                    >
                      <CircleFilledIcon
                        className={classNames(projectcss.all, sty.svg__ujRbs)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___5WYb2
                        )}
                      >
                        {
                          "Modernized ETL workflows, enabling real-time data integration pipelines providing data insights and improving stakeholder reporting turnaround"
                        }
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__roryp)}
                    >
                      <CircleFilledIcon
                        className={classNames(projectcss.all, sty.svg__zCoIf)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qdEn2
                        )}
                      >
                        {
                          "Brainstormed with researchers to align data systems with project objectives, to ensuring accuracy, consistency, and adherence to data governance and analytical standards, supporting strategic decision-making"
                        }
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__eJ4Vj)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__u9Qe5
                      )}
                    >
                      {"Health Data Engineer"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__gq8X6)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__svYs3
                        )}
                      >
                        {"Health Project Data Engineer"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__mthC
                        )}
                      >
                        <CalendarFilledIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___2CpCb
                          )}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__tJcxp
                          )}
                        >
                          {"04/2022 - Present"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__ocrcS
                        )}
                      >
                        <LocationFilledIcon
                          className={classNames(projectcss.all, sty.svg__r90Ox)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__tMbp
                          )}
                        >
                          {"Toronto, Canada"}
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__o8U1Y
                      )}
                    >
                      {
                        "Formulated and launched a data-driven decision support system, leveraging scenario modelling and predictive analytics to assess the impacts of global warming on health factors, driving actionable insights for research and policy decisions"
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__oPu9)}
                    >
                      <CircleFilledIcon
                        className={classNames(projectcss.all, sty.svg__uYq56)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bLr97
                        )}
                      >
                        {
                          "Acquired and managed large, complex datasets from diverse sources, utilizing a MongoDB-supported database to ensure scalable, e\ufb03cient data storage and seamless integration for advanced research and analytics"
                        }
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___1Ovuq
                      )}
                    >
                      <CircleFilledIcon
                        className={classNames(projectcss.all, sty.svg__dqpjv)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vVt1J
                        )}
                      >
                        {
                          "Conducted comprehensive data cleaning, preprocessing, and exploration using Python libraries (e.g., Pandas, NumPy, Matplotlib), laying the oundation for advanced analysis and delivering critical research insights"
                        }
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__yJ9RN)}
                    >
                      <CircleFilledIcon
                        className={classNames(projectcss.all, sty.svg__uVthI)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__t9OuS
                        )}
                      >
                        {
                          "Enhanced ETL workflows by re-engineering database structures and ETL pipelines, significantly enhancing data processing performance by 50% and ensuring high-quality, reliable outputs for critical analytical tasks"
                        }
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__zkg42)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lnG2Y
                    )}
                  >
                    {"Summary"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__npg2G
                    )}
                  >
                    {
                      "Dynamic and results-oriented Senior Data Engineer with proven expertise in designing, implementing, and optimizing ETL pipelines, data workflows, and big data solutions. Proficient in Python and SQL, with advanced knowledge of AWS services (e.g., S3, Lambda, RDS, Redshift, Kinesis, Glue, Athena) to architect scalable, resilient cloud-based data systems. Skilled in data modelling (star and dimensional schema), orchestration tools like Apache Airflow, and big data technologies such as Apache Spark and Hadoop. Delivered measurable improvements in ETL processing times, cost savings on cloud resources, and query performance. Adept at applying CI/CD practices using Jenkins, Git workflows, Docker and Kubernetes to streamline deployments, enhance e\ufb03ciency, and ensure system reliability. Recognized for implementing innovative, data-driven solutions that improve operatio"
                    }
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jJ73T
                    )}
                  >
                    {"Education"}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__a4IjI)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__aFis
                      )}
                    >
                      {"Bachelor of Science Computer Science"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gsrjg
                      )}
                    >
                      {"York University"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__aJiMr)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___7WkSa
                        )}
                      >
                        <CalendarFilledIcon
                          className={classNames(projectcss.all, sty.svg__g9IY)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__hzAf
                          )}
                        >
                          {"9/2018 - 08/2020"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__fwnxg
                        )}
                      >
                        <LocationFilledIcon
                          className={classNames(projectcss.all, sty.svg__w7Vvj)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__fpg93
                          )}
                        >
                          {"Toronto, Canada"}
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ohXrL)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__d0Hs5
                      )}
                    >
                      {"Master of Science Systems Engineering"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6OWr6
                      )}
                    >
                      {"Amirkabir University of Technology"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__pR8D)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__wlJRy
                        )}
                      >
                        <CalendarFilledIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___3YQuk
                          )}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___9Vj4W
                          )}
                        >
                          {"9/2013 - 01/2016"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__mMeml
                        )}
                      >
                        <LocationFilledIcon
                          className={classNames(projectcss.all, sty.svg__yXdo4)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___6H1Q2
                          )}
                        >
                          {"Tehran, Iran"}
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__lJ0Ou)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___75XMu
                      )}
                    >
                      {"Bachelor of Science Industrial Engineering"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___4Iaw0
                      )}
                    >
                      {"Amirkabir University of Technology"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__vMdgc)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__eev5V
                        )}
                      >
                        <CalendarFilledIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___2Q2N3
                          )}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__p2Irg
                          )}
                        >
                          {"9/2009- 06/2013"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__mgBlW
                        )}
                      >
                        <LocationFilledIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___6LKlZ
                          )}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__rEsn
                          )}
                        >
                          {"Tehran, Iran"}
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yyrPi
                    )}
                  >
                    {"Skills"}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__wjGdm)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eNwwu
                      )}
                    >
                      {"Programming Languages:"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__y1MTk
                      )}
                    >
                      {"Python, JavaScript, Java, Ruby"}
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__r0Kjr)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wN0Ox
                      )}
                    >
                      {"Databases:"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nFsk
                      )}
                    >
                      {"PostgreSQL, MySQL, MongoDB, DynamoDB"}
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ldXTi)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__sXw5O
                      )}
                    >
                      {"Cloud Platforms:"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eftjK
                      )}
                    >
                      {
                        "AWS S3, Redshift, RDS, Lambda, DMS, Kinesis, DMS,\nGlue, EMR, Athena, DynamoDB"
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__qjUcn)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__v4Yaj
                      )}
                    >
                      {"Data Modelling:"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pmjJ9
                      )}
                    >
                      {"Dimensional Modelling, Star & Snowflake Schema"}
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__lRx5Q)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gb4YI
                      )}
                    >
                      {"Version Control and Containerization:"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__t6Vum
                      )}
                    >
                      {"Git, GitHub, Docker, Kubernetes"}
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__j49Bf)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jnku4
                      )}
                    >
                      {"Data Engineering Tools:"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__sVze0
                      )}
                    >
                      {"Apache Spark, Hadoop, Airflow, Kafka"}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___0InSs)}>
            <button
              className={classNames(
                projectcss.all,
                projectcss.button,
                sty.button__lbwTu
              )}
              onClick={async event => {
                const $steps = {};

                $steps["goToHttpsAmirGhahariDevResumeAmirhesamGhahariCvPdf"] =
                  true
                    ? (() => {
                        const actionArgs = {
                          destination:
                            config.resumePdfUrl
                        };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                if (
                  $steps[
                    "goToHttpsAmirGhahariDevResumeAmirhesamGhahariCvPdf"
                  ] != null &&
                  typeof $steps[
                    "goToHttpsAmirGhahariDevResumeAmirhesamGhahariCvPdf"
                  ] === "object" &&
                  typeof $steps[
                    "goToHttpsAmirGhahariDevResumeAmirhesamGhahariCvPdf"
                  ].then === "function"
                ) {
                  $steps["goToHttpsAmirGhahariDevResumeAmirhesamGhahariCvPdf"] =
                    await $steps[
                      "goToHttpsAmirGhahariDevResumeAmirhesamGhahariCvPdf"
                    ];
                }

                $steps["invokeGlobalAction"] = true
                  ? (() => {
                      const actionArgs = {
                        args: [undefined, "Downloaded", undefined, 3, "top"]
                      };
                      return $globalActions[
                        "plasmic-antd5-config-provider.showNotification"
                      ]?.apply(null, [...actionArgs.args]);
                    })()
                  : undefined;
                if (
                  $steps["invokeGlobalAction"] != null &&
                  typeof $steps["invokeGlobalAction"] === "object" &&
                  typeof $steps["invokeGlobalAction"].then === "function"
                ) {
                  $steps["invokeGlobalAction"] =
                    await $steps["invokeGlobalAction"];
                }
              }}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___7FaPp
                )}
              >
                {"Download CV"}
              </div>
              <FileDownloadIcon
                className={classNames(projectcss.all, sty.svg__pdg92)}
                role={"img"}
              />
            </button>
          </div>
          <div
            data-plasmic-name={"socialMediaContainer"}
            data-plasmic-override={overrides.socialMediaContainer}
            className={classNames(projectcss.all, sty.socialMediaContainer)}
          >
            <PlasmicLink__
              data-plasmic-name={"instagramLink"}
              data-plasmic-override={overrides.instagramLink}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.instagramLink
              )}
              component={Link}
              href={config.instagram}
              legacyBehavior={false}
              platform={"nextjs"}
              target={"_blank"}
            >
              <BrandInstagramIcon
                className={classNames(projectcss.all, sty.svg__jSp6D)}
                role={"img"}
              />
            </PlasmicLink__>
            <PlasmicLink__
              data-plasmic-name={"facebookLink"}
              data-plasmic-override={overrides.facebookLink}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.facebookLink
              )}
              component={Link}
              href={config.facebook}
              legacyBehavior={false}
              platform={"nextjs"}
              target={"_blank"}
            >
              <BrandFacebookFilledIcon
                className={classNames(projectcss.all, sty.svg__qxVqW)}
                role={"img"}
              />
            </PlasmicLink__>
            <PlasmicLink__
              data-plasmic-name={"linkedinLink"}
              data-plasmic-override={overrides.linkedinLink}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.linkedinLink
              )}
              component={Link}
              href={config.linkedin}
              legacyBehavior={false}
              platform={"nextjs"}
              target={"_blank"}
            >
              <BrandLinkedinIcon2
                className={classNames(projectcss.all, sty.svg__gxA8N)}
                role={"img"}
              />
            </PlasmicLink__>
            <PlasmicLink__
              data-plasmic-name={"githubLink"}
              data-plasmic-override={overrides.githubLink}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.githubLink
              )}
              component={Link}
              href={config.github}
              legacyBehavior={false}
              platform={"nextjs"}
              target={"_blank"}
            >
              <BrandGithubFilledIcon
                className={classNames(projectcss.all, sty.svg__mG5Pc)}
                role={"img"}
              />
            </PlasmicLink__>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  mainPage: [
    "mainPage",
    "pagesLinksContainer",
    "link",
    "projects",
    "aboutLink",
    "skills",
    "resume",
    "contact",
    "socialMediaContainer",
    "instagramLink",
    "facebookLink",
    "linkedinLink",
    "githubLink"
  ],
  pagesLinksContainer: [
    "pagesLinksContainer",
    "link",
    "projects",
    "aboutLink",
    "skills",
    "resume"
  ],
  link: ["link"],
  projects: ["projects"],
  aboutLink: ["aboutLink"],
  skills: ["skills"],
  resume: ["resume"],
  contact: ["contact"],
  socialMediaContainer: [
    "socialMediaContainer",
    "instagramLink",
    "facebookLink",
    "linkedinLink",
    "githubLink"
  ],
  instagramLink: ["instagramLink"],
  facebookLink: ["facebookLink"],
  linkedinLink: ["linkedinLink"],
  githubLink: ["githubLink"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  mainPage: "div";
  pagesLinksContainer: "div";
  link: "a";
  projects: "a";
  aboutLink: "a";
  skills: "a";
  resume: "a";
  contact: "a";
  socialMediaContainer: "div";
  instagramLink: "a";
  facebookLink: "a";
  linkedinLink: "a";
  githubLink: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicResume__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicResume__VariantsArgs;
    args?: PlasmicResume__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicResume__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicResume__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicResume__ArgProps,
          internalVariantPropNames: PlasmicResume__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicResume__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "mainPage") {
    func.displayName = "PlasmicResume";
  } else {
    func.displayName = `PlasmicResume.${nodeName}`;
  }
  return func;
}

export const PlasmicResume = Object.assign(
  // Top-level PlasmicResume renders the root element
  makeNodeComponent("mainPage"),
  {
    // Helper components rendering sub-elements
    pagesLinksContainer: makeNodeComponent("pagesLinksContainer"),
    link: makeNodeComponent("link"),
    projects: makeNodeComponent("projects"),
    aboutLink: makeNodeComponent("aboutLink"),
    skills: makeNodeComponent("skills"),
    resume: makeNodeComponent("resume"),
    contact: makeNodeComponent("contact"),
    socialMediaContainer: makeNodeComponent("socialMediaContainer"),
    instagramLink: makeNodeComponent("instagramLink"),
    facebookLink: makeNodeComponent("facebookLink"),
    linkedinLink: makeNodeComponent("linkedinLink"),
    githubLink: makeNodeComponent("githubLink"),

    // Metadata about props expected for PlasmicResume
    internalVariantProps: PlasmicResume__VariantProps,
    internalArgProps: PlasmicResume__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pagePath: "/resume",
      searchParams: {},
      params: {}
    })
  }
);

export default PlasmicResume;
/* prettier-ignore-end */
