/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1MA8tVtTQ6ARhYAYML2fXH
// Component: izP4e4TEQvm4

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/styleTokensProvider
import { config } from "@/lib/config"; // MANUALLY ADDED: re-add after npx plasmic sync

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/projectcss
import sty from "./PlasmicSkills.module.css"; // plasmic-import: izP4e4TEQvm4/css

import CodingHtmlSvgrepoComSvgIcon from "./icons/PlasmicIcon__CodingHtmlSvgrepoComSvg"; // plasmic-import: gOGEOMzO-5dH/icon
import CircleFilledIcon from "./icons/PlasmicIcon__CircleFilled"; // plasmic-import: MtO7pWUwIhVA/icon
import CircleFilledIcon2 from "../library_tabler_3_2_icons/icons/PlasmicIcon__CircleFilled"; // plasmic-import: Z45_TKGL7Jxg/icon
import DatabaseSvgrepoComSvgIcon from "./icons/PlasmicIcon__DatabaseSvgrepoComSvg"; // plasmic-import: f1KXDkDsDuA9/icon
import DataReportSvgrepoComSvgIcon from "./icons/PlasmicIcon__DataReportSvgrepoComSvg"; // plasmic-import: 8KquinGZmziR/icon
import AwsKinesisSvgrepoComSvgIcon from "./icons/PlasmicIcon__AwsKinesisSvgrepoComSvg"; // plasmic-import: x8sW9Otz0xvE/icon
import CloudComputingAiSvgrepoComSvgIcon from "./icons/PlasmicIcon__CloudComputingAiSvgrepoComSvg"; // plasmic-import: eZ85Bg5qyXqB/icon
import CloudDatabaseHostingSvgrepoComSvgIcon from "./icons/PlasmicIcon__CloudDatabaseHostingSvgrepoComSvg"; // plasmic-import: Bssew3GnfDVB/icon
import ComputeEngineSvgrepoComSvgIcon from "./icons/PlasmicIcon__ComputeEngineSvgrepoComSvg"; // plasmic-import: vYp4UoM46He0/icon
import CodingHtmlSvgrepoCom1SvgIcon from "./icons/PlasmicIcon__CodingHtmlSvgrepoCom1Svg"; // plasmic-import: MIHq_wYj0sQV/icon
import WebsiteQuestionSvgrepoComSvgIcon from "./icons/PlasmicIcon__WebsiteQuestionSvgrepoComSvg"; // plasmic-import: vWB2ywiSiYFT/icon
import BrandInstagramIcon from "./icons/PlasmicIcon__BrandInstagram"; // plasmic-import: sPs8xq4XDSB7/icon
import BrandFacebookFilledIcon from "./icons/PlasmicIcon__BrandFacebookFilled"; // plasmic-import: gYHB8kOr7qS6/icon
import BrandLinkedinIcon from "./icons/PlasmicIcon__BrandLinkedin"; // plasmic-import: YL_7Hzz6ddJB/icon
import BrandGithubFilledIcon from "./icons/PlasmicIcon__BrandGithubFilled"; // plasmic-import: jgc3Mi7tL_Sx/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q: any, $ctx: any) {
  return {
    title: "skills",

    openGraph: {
      title: "skills"
    },
    twitter: {
      card: "summary",
      title: "skills"
    }
  };
}

createPlasmicElementProxy;

export type PlasmicSkills__VariantMembers = {};
export type PlasmicSkills__VariantsArgs = {};
type VariantPropType = keyof PlasmicSkills__VariantsArgs;
export const PlasmicSkills__VariantProps = new Array<VariantPropType>();

export type PlasmicSkills__ArgsType = {};
type ArgPropType = keyof PlasmicSkills__ArgsType;
export const PlasmicSkills__ArgProps = new Array<ArgPropType>();

export type PlasmicSkills__OverridesType = {
  mainPage?: Flex__<"div">;
  pagesLinksContainer?: Flex__<"div">;
  link?: Flex__<"a"> & Partial<LinkProps>;
  projects?: Flex__<"a"> & Partial<LinkProps>;
  aboutLink?: Flex__<"a"> & Partial<LinkProps>;
  skills?: Flex__<"a"> & Partial<LinkProps>;
  resume?: Flex__<"a"> & Partial<LinkProps>;
  contact?: Flex__<"a"> & Partial<LinkProps>;
  foreground?: Flex__<"div">;
  h2?: Flex__<"h2">;
  columns?: Flex__<"div">;
  socialMediaContainer?: Flex__<"div">;
  instagramLink?: Flex__<"a"> & Partial<LinkProps>;
  facebookLink?: Flex__<"a"> & Partial<LinkProps>;
  linkedinLink?: Flex__<"a"> & Partial<LinkProps>;
  githubLink?: Flex__<"a"> & Partial<LinkProps>;
};

export interface DefaultSkillsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSkills__RenderFunc(props: {
  variants: PlasmicSkills__VariantsArgs;
  args: PlasmicSkills__ArgsType;
  overrides: PlasmicSkills__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"mainPage"}
          data-plasmic-override={overrides.mainPage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.mainPage
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__dLkEj)}>
            <div
              data-plasmic-name={"pagesLinksContainer"}
              data-plasmic-override={overrides.pagesLinksContainer}
              className={classNames(projectcss.all, sty.pagesLinksContainer)}
            >
              <PlasmicLink__
                data-plasmic-name={"link"}
                data-plasmic-override={overrides.link}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link
                )}
                component={Link}
                href={`/`}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"HOME"}
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"projects"}
                data-plasmic-override={overrides.projects}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.projects
                )}
                component={Link}
                href={`/work-experience`}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"Work Experience"}
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"aboutLink"}
                data-plasmic-override={overrides.aboutLink}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.aboutLink
                )}
                component={Link}
                href={`/about-me`}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"About Me"}
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"skills"}
                data-plasmic-override={overrides.skills}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.skills
                )}
                component={Link}
                href={`/skills`}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"Skills"}
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"resume"}
                data-plasmic-override={overrides.resume}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.resume
                )}
                component={Link}
                href={`/resume`}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"Resume"}
              </PlasmicLink__>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__mhsZe)} />

            <PlasmicLink__
              data-plasmic-name={"contact"}
              data-plasmic-override={overrides.contact}
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.contact
              )}
              component={Link}
              href={`/contact`}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Contact Me"}
            </PlasmicLink__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__r7Emv)}>
            <div className={classNames(projectcss.all, sty.freeBox__gPleP)}>
              <div
                data-plasmic-name={"foreground"}
                data-plasmic-override={overrides.foreground}
                className={classNames(projectcss.all, sty.foreground)}
              >
                <h2
                  data-plasmic-name={"h2"}
                  data-plasmic-override={overrides.h2}
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2
                  )}
                >
                  {"Technical Skills and Stack"}
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___5MNd1
                  )}
                >
                  {
                    "To deliver reliable, scalable, and high-performance data solutions, I leverage a broad and modern technical skill set across software engineering, data engineering, cloud architecture, and analytics. My technical expertise enables me to design secure, scalable, and cost-effective data platforms that support analytics, reporting, and advanced data science initiatives."
                  }
                </div>
              </div>
              <div
                data-plasmic-name={"columns"}
                data-plasmic-override={overrides.columns}
                className={classNames(projectcss.all, sty.columns)}
              >
                <div className={classNames(projectcss.all, sty.column__k9LoW)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__vYmtC)}
                  >
                    <CodingHtmlSvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg__btI5U)}
                      role={"img"}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__eo6T)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xZqQm
                        )}
                      >
                        {"Programming & Version Control"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___9XOAd
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__eUoci
                          )}
                        >
                          <CircleFilledIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__sdL5G
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__aaLcO
                            )}
                          >
                            {"Python"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__mW3Un
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__nK1Oo
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__bf5C
                            )}
                          >
                            {"Ruby"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ipfRn
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__rXaQ9
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__pheoZ
                            )}
                          >
                            {"JavaScript"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__isdji
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg___9NGpH
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___7UFTs
                            )}
                          >
                            {"Git & GitHub"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___8XW7N
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__rcnp4
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___2YsK3
                            )}
                          >
                            {"Jenkins"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__iKLbP
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__ogMKz
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__t71Yn
                            )}
                          >
                            {"Docker & CI/CD workflows"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__fmRxs)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___4XttC)}
                  >
                    <DatabaseSvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg__rFmnJ)}
                      role={"img"}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__myzD4)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ouDXh
                        )}
                      >
                        {"Data & Query Technologies"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___98Zll
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__oc3Fm
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__sgt5I
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ymAUi
                            )}
                          >
                            {"SQL"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__igdKw
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__l6RX1
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__psBbL
                            )}
                          >
                            {"DBT"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__lbdLz
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__z4Qb5
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__yBc0E
                            )}
                          >
                            {"Apache Spark"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__c9K1Y
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__rrg23
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__tXwV
                            )}
                          >
                            {"Apache Airflow"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__oom7A
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__eqkc4
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__oEyF
                            )}
                          >
                            {"Data modeling (dimensional and star schemas)"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__yu2X)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___2Ujcp)}
                  >
                    <DataReportSvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg__g0VjC)}
                      role={"img"}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__wv9Zm)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mzsD
                        )}
                      >
                        {"Business Intelligence & Analytics"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__fl2Gx
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__lbSeT
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__rcZdy
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___8Io06
                            )}
                          >
                            {"Tableau"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__q8Jcs
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__oNbB6
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__mf8X9
                            )}
                          >
                            {"Metabase"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__eh6Zj
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__huCG
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__nqlvo
                            )}
                          >
                            {"Amazon QuickSight"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___2WpxV
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__wf8U
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__c5Buh
                            )}
                          >
                            {"Power BI"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__vyPqH
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__aT1P8
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ys1Xn
                            )}
                          >
                            {"Dashboard design and KPI development"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__hSOw)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__n4TBx)}
                  >
                    <AwsKinesisSvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg___8UVpB)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___9BbzZ
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lJfXx
                        )}
                      >
                        {"Real-Time & Streaming Systems"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__boBmk
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___50W1V
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__niuSy
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__zdjGi
                            )}
                          >
                            {"Apache Kafka"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ul19Q
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__ecpZ1
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__yqNVg
                            )}
                          >
                            {"AWS Kinesis Firehose"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__hQrhx
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__bnHnW
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__im3VX
                            )}
                          >
                            {"AWS Kinesis Data Streams"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__fvAi2
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__adJAz
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ddH1
                            )}
                          >
                            {"Event-driven architectures"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__zCaqt)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___9Gneu)}
                  >
                    <CloudComputingAiSvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg__gVqKy)}
                      role={"img"}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__g2Xmd)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hDsOd
                        )}
                      >
                        {"Machine Learning & AI"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__a0Iab
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___2371Y
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__gzP1
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___5PCv8
                            )}
                          >
                            {"AWS SageMaker"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__zPf44
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__kPopd
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__xWrGn
                            )}
                          >
                            {"AWS Rekognition"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__aXJf
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__b6ER
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___3Bq6
                            )}
                          >
                            {"Scikit-learn"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__kneBl
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__of0E6
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__hlVoc
                            )}
                          >
                            {"Model integration with data pipelines"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__ua2I8)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__sbrFn)}
                  >
                    <CloudDatabaseHostingSvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg__cRuGk)}
                      role={"img"}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__ptE0F)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__v6R0O
                        )}
                      >
                        {"AWS Databases & Storage"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__gLBhg
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__tqfNs
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__k8LxI
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__wKjFx
                            )}
                          >
                            {"AWS S3"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__aCnLz
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__agyoh
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___9Ugxj
                            )}
                          >
                            {"Redshift"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___1LhjR
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__dF2I6
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__r1Mn
                            )}
                          >
                            {"DynamoDB"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__fxbUc
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__s9MMj
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__cJGw
                            )}
                          >
                            {"RDS & Aurora"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__pJhU
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__crmLm
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__xjc4X
                            )}
                          >
                            {"Data lake and warehouse design"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__etTBk)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__oMsXc)}
                  >
                    <ComputeEngineSvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg___15Vmw)}
                      role={"img"}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__yZewt)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___4S8Ar
                        )}
                      >
                        {"AWS Compute & Infrastructure"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__cdNqf
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ohcZ
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__tHp6
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ecocB
                            )}
                          >
                            {"AWS Lambda"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__grM
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__hD3Lz
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__tZ8Wv
                            )}
                          >
                            {"AWS EC2"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__yxyaF
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__sxGl
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__hXDzC
                            )}
                          >
                            {"AWS ECS"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__egT0K
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__oS0Sz
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__dHind
                            )}
                          >
                            {"Elastic Load Balancer"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__g7JUa
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__shxSu
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__hepam
                            )}
                          >
                            {"Serverless and containerized systems"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__uZLuR)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__y2WU)}
                  >
                    <CodingHtmlSvgrepoCom1SvgIcon
                      className={classNames(projectcss.all, sty.svg__ic1Ha)}
                      role={"img"}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__ktc5I)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hvI6W
                        )}
                      >
                        {"AWS Data Engineering Services"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__yteTn
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__n7Hrf
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__bGPzz
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__mLvEk
                            )}
                          >
                            {"AWS Glue"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__gIf2P
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg___9X10N
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___4Ehn
                            )}
                          >
                            {"AWS DMS"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__lhKnq
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__erQhn
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___7PFb1
                            )}
                          >
                            {"Amazon OpenSearch"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__thbog
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__uWz2W
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__dzmUp
                            )}
                          >
                            {"Lake Formation"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___3BAec
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__dXzTk
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__kJjaA
                            )}
                          >
                            {"Data governance and cataloging"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__scilf)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___81TBl)}
                  >
                    <WebsiteQuestionSvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg__sD2Hp)}
                      role={"img"}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__xxckM)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__dqYtS
                        )}
                      >
                        {"Web & Integration Services"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__tUqat
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__kSfva
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg___8TaxW
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__pdBlQ
                            )}
                          >
                            {"AWS API Gateway"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___0Cw5T
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg___4A3Vo
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__vkqQi
                            )}
                          >
                            {"AWS CloudFront"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__mCes5
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__xHpAg
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__i9KsB
                            )}
                          >
                            {"Route 53"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__cuJQd
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__wCGoQ
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__fyOcg
                            )}
                          >
                            {"SQS, SNS, EventBridge"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__vyGLi
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__uuZ7P
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ujWwk
                            )}
                          >
                            {"AWS VPC"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__loUVq
                          )}
                        >
                          <CircleFilledIcon2
                            className={classNames(
                              projectcss.all,
                              sty.svg__adRCv
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__rvpUn
                            )}
                          >
                            {"AWS CloudFormation"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"socialMediaContainer"}
            data-plasmic-override={overrides.socialMediaContainer}
            className={classNames(projectcss.all, sty.socialMediaContainer)}
          >
            <PlasmicLink__
              data-plasmic-name={"instagramLink"}
              data-plasmic-override={overrides.instagramLink}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.instagramLink
              )}
              component={Link}
              href={config.instagram}
              legacyBehavior={false}
              platform={"nextjs"}
              target={"_blank"}
            >
              <BrandInstagramIcon
                className={classNames(projectcss.all, sty.svg__ma1O2)}
                role={"img"}
              />
            </PlasmicLink__>
            <PlasmicLink__
              data-plasmic-name={"facebookLink"}
              data-plasmic-override={overrides.facebookLink}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.facebookLink
              )}
              component={Link}
              href={config.facebook}
              legacyBehavior={false}
              platform={"nextjs"}
              target={"_blank"}
            >
              <BrandFacebookFilledIcon
                className={classNames(projectcss.all, sty.svg__zqh3)}
                role={"img"}
              />
            </PlasmicLink__>
            <PlasmicLink__
              data-plasmic-name={"linkedinLink"}
              data-plasmic-override={overrides.linkedinLink}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.linkedinLink
              )}
              component={Link}
              href={config.linkedin}
              legacyBehavior={false}
              platform={"nextjs"}
              target={"_blank"}
            >
              <BrandLinkedinIcon
                className={classNames(projectcss.all, sty.svg__sbJ7)}
                role={"img"}
              />
            </PlasmicLink__>
            <PlasmicLink__
              data-plasmic-name={"githubLink"}
              data-plasmic-override={overrides.githubLink}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.githubLink
              )}
              component={Link}
              href={config.github}
              legacyBehavior={false}
              platform={"nextjs"}
              target={"_blank"}
            >
              <BrandGithubFilledIcon
                className={classNames(projectcss.all, sty.svg__jmd21)}
                role={"img"}
              />
            </PlasmicLink__>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  mainPage: [
    "mainPage",
    "pagesLinksContainer",
    "link",
    "projects",
    "aboutLink",
    "skills",
    "resume",
    "contact",
    "foreground",
    "h2",
    "columns",
    "socialMediaContainer",
    "instagramLink",
    "facebookLink",
    "linkedinLink",
    "githubLink"
  ],
  pagesLinksContainer: [
    "pagesLinksContainer",
    "link",
    "projects",
    "aboutLink",
    "skills",
    "resume"
  ],
  link: ["link"],
  projects: ["projects"],
  aboutLink: ["aboutLink"],
  skills: ["skills"],
  resume: ["resume"],
  contact: ["contact"],
  foreground: ["foreground", "h2"],
  h2: ["h2"],
  columns: ["columns"],
  socialMediaContainer: [
    "socialMediaContainer",
    "instagramLink",
    "facebookLink",
    "linkedinLink",
    "githubLink"
  ],
  instagramLink: ["instagramLink"],
  facebookLink: ["facebookLink"],
  linkedinLink: ["linkedinLink"],
  githubLink: ["githubLink"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  mainPage: "div";
  pagesLinksContainer: "div";
  link: "a";
  projects: "a";
  aboutLink: "a";
  skills: "a";
  resume: "a";
  contact: "a";
  foreground: "div";
  h2: "h2";
  columns: "div";
  socialMediaContainer: "div";
  instagramLink: "a";
  facebookLink: "a";
  linkedinLink: "a";
  githubLink: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSkills__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSkills__VariantsArgs;
    args?: PlasmicSkills__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSkills__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSkills__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSkills__ArgProps,
          internalVariantPropNames: PlasmicSkills__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSkills__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "mainPage") {
    func.displayName = "PlasmicSkills";
  } else {
    func.displayName = `PlasmicSkills.${nodeName}`;
  }
  return func;
}

export const PlasmicSkills = Object.assign(
  // Top-level PlasmicSkills renders the root element
  makeNodeComponent("mainPage"),
  {
    // Helper components rendering sub-elements
    pagesLinksContainer: makeNodeComponent("pagesLinksContainer"),
    link: makeNodeComponent("link"),
    projects: makeNodeComponent("projects"),
    aboutLink: makeNodeComponent("aboutLink"),
    skills: makeNodeComponent("skills"),
    resume: makeNodeComponent("resume"),
    contact: makeNodeComponent("contact"),
    foreground: makeNodeComponent("foreground"),
    h2: makeNodeComponent("h2"),
    columns: makeNodeComponent("columns"),
    socialMediaContainer: makeNodeComponent("socialMediaContainer"),
    instagramLink: makeNodeComponent("instagramLink"),
    facebookLink: makeNodeComponent("facebookLink"),
    linkedinLink: makeNodeComponent("linkedinLink"),
    githubLink: makeNodeComponent("githubLink"),

    // Metadata about props expected for PlasmicSkills
    internalVariantProps: PlasmicSkills__VariantProps,
    internalArgProps: PlasmicSkills__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pagePath: "/skills",
      searchParams: {},
      params: {}
    })
  }
);

export default PlasmicSkills;
/* prettier-ignore-end */
