/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1MA8tVtTQ6ARhYAYML2fXH

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariants_1KymR9FqP5Og } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 1kymR9fqP5OG/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariants_1KymR9FqP5Og
});
