/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1MA8tVtTQ6ARhYAYML2fXH
// Component: J5h4tNKI-ymi

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/styleTokensProvider
import { config } from "@/lib/config"; // MANUALLY ADDED: re-add after npx plasmic sync

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/projectcss
import sty from "./PlasmicWebsiteFooter.module.css"; // plasmic-import: J5h4tNKI-ymi/css

import BrandInstagramIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__BrandInstagram"; // plasmic-import: mGzbOin0yfZQ/icon
import BrandFacebookFilledIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__BrandFacebookFilled"; // plasmic-import: QXaxLXwY62qy/icon
import BrandLinkedinIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__BrandLinkedin"; // plasmic-import: KshNwg5oK9bk/icon
import BrandGithubFilledIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__BrandGithubFilled"; // plasmic-import: bKFzb-NyWBDz/icon
import ArrowBigRightFilledIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__ArrowBigRightFilled"; // plasmic-import: 6uggRkEYeTKa/icon

createPlasmicElementProxy;

export type PlasmicWebsiteFooter__VariantMembers = {};
export type PlasmicWebsiteFooter__VariantsArgs = {};
type VariantPropType = keyof PlasmicWebsiteFooter__VariantsArgs;
export const PlasmicWebsiteFooter__VariantProps = new Array<VariantPropType>();

export type PlasmicWebsiteFooter__ArgsType = {};
type ArgPropType = keyof PlasmicWebsiteFooter__ArgsType;
export const PlasmicWebsiteFooter__ArgProps = new Array<ArgPropType>();

export type PlasmicWebsiteFooter__OverridesType = {
  mainFooterContainer?: Flex__<"div">;
  footerContainer?: Flex__<"div">;
  myPictureContainer?: Flex__<"div">;
  meSummaryContainer?: Flex__<"div">;
  smallPhoto?: Flex__<typeof PlasmicImg__>;
  detailsStack?: Flex__<"div">;
  nameText?: Flex__<"h1">;
  titleText?: Flex__<"h1">;
  socialMediaContainer?: Flex__<"div">;
  instagramLink?: Flex__<"a"> & Partial<LinkProps>;
  facebookLink?: Flex__<"a"> & Partial<LinkProps>;
  linkedinLink?: Flex__<"a"> & Partial<LinkProps>;
  githubLink?: Flex__<"a"> & Partial<LinkProps>;
  inTouchContainer?: Flex__<"div">;
  inTouchContainer2?: Flex__<"div">;
  h1?: Flex__<"h1">;
  contactContainer?: Flex__<"div">;
  emailFull?: Flex__<"div">;
  emailContianer?: Flex__<"div">;
  emailAddress?: Flex__<"div">;
  callMeStack?: Flex__<"div">;
  phoneContainer?: Flex__<"div">;
};

export interface DefaultWebsiteFooterProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicWebsiteFooter__RenderFunc(props: {
  variants: PlasmicWebsiteFooter__VariantsArgs;
  args: PlasmicWebsiteFooter__ArgsType;
  overrides: PlasmicWebsiteFooter__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"mainFooterContainer"}
      data-plasmic-override={overrides.mainFooterContainer}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.mainFooterContainer
      )}
    >
      <div
        data-plasmic-name={"footerContainer"}
        data-plasmic-override={overrides.footerContainer}
        className={classNames(projectcss.all, sty.footerContainer)}
      >
        <div
          data-plasmic-name={"myPictureContainer"}
          data-plasmic-override={overrides.myPictureContainer}
          className={classNames(projectcss.all, sty.myPictureContainer)}
        >
          <div
            data-plasmic-name={"meSummaryContainer"}
            data-plasmic-override={overrides.meSummaryContainer}
            className={classNames(projectcss.all, sty.meSummaryContainer)}
          >
            <PlasmicImg__
              data-plasmic-name={"smallPhoto"}
              data-plasmic-override={overrides.smallPhoto}
              alt={""}
              className={classNames(sty.smallPhoto)}
              displayHeight={"auto"}
              displayMaxHeight={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "70%"
                  : "80%"
              }
              displayMaxWidth={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "50%"
                  : "30%"
              }
              displayMinHeight={"50%"}
              displayMinWidth={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "40%"
                  : "20%"
              }
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/amir_ghahari_website/images/smallPicPng.png",
                fullWidth: 1706,
                fullHeight: 1153,
                aspectRatio: undefined
              }}
            />

            <div
              data-plasmic-name={"detailsStack"}
              data-plasmic-override={overrides.detailsStack}
              className={classNames(projectcss.all, sty.detailsStack)}
            >
              <h1
                data-plasmic-name={"nameText"}
                data-plasmic-override={overrides.nameText}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.nameText
                )}
              >
                {config.name}
              </h1>
              <h1
                data-plasmic-name={"titleText"}
                data-plasmic-override={overrides.titleText}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.titleText
                )}
              >
                {`${config.jobTitle} at ${config.company}`}
              </h1>
            </div>
          </div>
          <div
            data-plasmic-name={"socialMediaContainer"}
            data-plasmic-override={overrides.socialMediaContainer}
            className={classNames(projectcss.all, sty.socialMediaContainer)}
          >
            <PlasmicLink__
              data-plasmic-name={"instagramLink"}
              data-plasmic-override={overrides.instagramLink}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.instagramLink
              )}
              component={Link}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              <BrandInstagramIcon
                className={classNames(projectcss.all, sty.svg__rjjr8)}
                role={"img"}
              />
            </PlasmicLink__>
            <PlasmicLink__
              data-plasmic-name={"facebookLink"}
              data-plasmic-override={overrides.facebookLink}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.facebookLink
              )}
              component={Link}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              <BrandFacebookFilledIcon
                className={classNames(projectcss.all, sty.svg__vPkTf)}
                role={"img"}
              />
            </PlasmicLink__>
            <PlasmicLink__
              data-plasmic-name={"linkedinLink"}
              data-plasmic-override={overrides.linkedinLink}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.linkedinLink
              )}
              component={Link}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              <BrandLinkedinIcon
                className={classNames(projectcss.all, sty.svg__qBeXp)}
                role={"img"}
              />
            </PlasmicLink__>
            <PlasmicLink__
              data-plasmic-name={"githubLink"}
              data-plasmic-override={overrides.githubLink}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.githubLink
              )}
              component={Link}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              <BrandGithubFilledIcon
                className={classNames(projectcss.all, sty.svg__mzf43)}
                role={"img"}
              />
            </PlasmicLink__>
          </div>
        </div>
        <div
          data-plasmic-name={"inTouchContainer"}
          data-plasmic-override={overrides.inTouchContainer}
          className={classNames(projectcss.all, sty.inTouchContainer)}
        >
          <div
            data-plasmic-name={"inTouchContainer2"}
            data-plasmic-override={overrides.inTouchContainer2}
            className={classNames(projectcss.all, sty.inTouchContainer2)}
          >
            <h1
              data-plasmic-name={"h1"}
              data-plasmic-override={overrides.h1}
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.__wab_text,
                sty.h1
              )}
            >
              {"Get in touch"}
            </h1>
            <ArrowBigRightFilledIcon
              className={classNames(projectcss.all, sty.svg__ajIZk)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"contactContainer"}
            data-plasmic-override={overrides.contactContainer}
            className={classNames(projectcss.all, sty.contactContainer)}
          >
            <div
              data-plasmic-name={"emailFull"}
              data-plasmic-override={overrides.emailFull}
              className={classNames(projectcss.all, sty.emailFull)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wrPyI
                )}
              >
                {"Email Me:"}
              </div>
              <div
                data-plasmic-name={"emailContianer"}
                data-plasmic-override={overrides.emailContianer}
                className={classNames(projectcss.all, sty.emailContianer)}
              >
                <div
                  data-plasmic-name={"emailAddress"}
                  data-plasmic-override={overrides.emailAddress}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.emailAddress
                  )}
                >
                  {config.email}
                </div>
                <ArrowBigRightFilledIcon
                  className={classNames(projectcss.all, sty.svg__lq96B)}
                  role={"img"}
                />
              </div>
            </div>
            <div
              data-plasmic-name={"callMeStack"}
              data-plasmic-override={overrides.callMeStack}
              className={classNames(projectcss.all, sty.callMeStack)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__u7PB0
                )}
              >
                {"Call me:"}
              </div>
              <div
                data-plasmic-name={"phoneContainer"}
                data-plasmic-override={overrides.phoneContainer}
                className={classNames(projectcss.all, sty.phoneContainer)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uEqs9
                  )}
                >
                  {config.phoneShort}
                </div>
                <ArrowBigRightFilledIcon
                  className={classNames(projectcss.all, sty.svg__vcobh)}
                  role={"img"}
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  mainFooterContainer: [
    "mainFooterContainer",
    "footerContainer",
    "myPictureContainer",
    "meSummaryContainer",
    "smallPhoto",
    "detailsStack",
    "nameText",
    "titleText",
    "socialMediaContainer",
    "instagramLink",
    "facebookLink",
    "linkedinLink",
    "githubLink",
    "inTouchContainer",
    "inTouchContainer2",
    "h1",
    "contactContainer",
    "emailFull",
    "emailContianer",
    "emailAddress",
    "callMeStack",
    "phoneContainer"
  ],
  footerContainer: [
    "footerContainer",
    "myPictureContainer",
    "meSummaryContainer",
    "smallPhoto",
    "detailsStack",
    "nameText",
    "titleText",
    "socialMediaContainer",
    "instagramLink",
    "facebookLink",
    "linkedinLink",
    "githubLink",
    "inTouchContainer",
    "inTouchContainer2",
    "h1",
    "contactContainer",
    "emailFull",
    "emailContianer",
    "emailAddress",
    "callMeStack",
    "phoneContainer"
  ],
  myPictureContainer: [
    "myPictureContainer",
    "meSummaryContainer",
    "smallPhoto",
    "detailsStack",
    "nameText",
    "titleText",
    "socialMediaContainer",
    "instagramLink",
    "facebookLink",
    "linkedinLink",
    "githubLink"
  ],
  meSummaryContainer: [
    "meSummaryContainer",
    "smallPhoto",
    "detailsStack",
    "nameText",
    "titleText"
  ],
  smallPhoto: ["smallPhoto"],
  detailsStack: ["detailsStack", "nameText", "titleText"],
  nameText: ["nameText"],
  titleText: ["titleText"],
  socialMediaContainer: [
    "socialMediaContainer",
    "instagramLink",
    "facebookLink",
    "linkedinLink",
    "githubLink"
  ],
  instagramLink: ["instagramLink"],
  facebookLink: ["facebookLink"],
  linkedinLink: ["linkedinLink"],
  githubLink: ["githubLink"],
  inTouchContainer: [
    "inTouchContainer",
    "inTouchContainer2",
    "h1",
    "contactContainer",
    "emailFull",
    "emailContianer",
    "emailAddress",
    "callMeStack",
    "phoneContainer"
  ],
  inTouchContainer2: ["inTouchContainer2", "h1"],
  h1: ["h1"],
  contactContainer: [
    "contactContainer",
    "emailFull",
    "emailContianer",
    "emailAddress",
    "callMeStack",
    "phoneContainer"
  ],
  emailFull: ["emailFull", "emailContianer", "emailAddress"],
  emailContianer: ["emailContianer", "emailAddress"],
  emailAddress: ["emailAddress"],
  callMeStack: ["callMeStack", "phoneContainer"],
  phoneContainer: ["phoneContainer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  mainFooterContainer: "div";
  footerContainer: "div";
  myPictureContainer: "div";
  meSummaryContainer: "div";
  smallPhoto: typeof PlasmicImg__;
  detailsStack: "div";
  nameText: "h1";
  titleText: "h1";
  socialMediaContainer: "div";
  instagramLink: "a";
  facebookLink: "a";
  linkedinLink: "a";
  githubLink: "a";
  inTouchContainer: "div";
  inTouchContainer2: "div";
  h1: "h1";
  contactContainer: "div";
  emailFull: "div";
  emailContianer: "div";
  emailAddress: "div";
  callMeStack: "div";
  phoneContainer: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicWebsiteFooter__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicWebsiteFooter__VariantsArgs;
    args?: PlasmicWebsiteFooter__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicWebsiteFooter__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicWebsiteFooter__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicWebsiteFooter__ArgProps,
          internalVariantPropNames: PlasmicWebsiteFooter__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicWebsiteFooter__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "mainFooterContainer") {
    func.displayName = "PlasmicWebsiteFooter";
  } else {
    func.displayName = `PlasmicWebsiteFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicWebsiteFooter = Object.assign(
  // Top-level PlasmicWebsiteFooter renders the root element
  makeNodeComponent("mainFooterContainer"),
  {
    // Helper components rendering sub-elements
    footerContainer: makeNodeComponent("footerContainer"),
    myPictureContainer: makeNodeComponent("myPictureContainer"),
    meSummaryContainer: makeNodeComponent("meSummaryContainer"),
    smallPhoto: makeNodeComponent("smallPhoto"),
    detailsStack: makeNodeComponent("detailsStack"),
    nameText: makeNodeComponent("nameText"),
    titleText: makeNodeComponent("titleText"),
    socialMediaContainer: makeNodeComponent("socialMediaContainer"),
    instagramLink: makeNodeComponent("instagramLink"),
    facebookLink: makeNodeComponent("facebookLink"),
    linkedinLink: makeNodeComponent("linkedinLink"),
    githubLink: makeNodeComponent("githubLink"),
    inTouchContainer: makeNodeComponent("inTouchContainer"),
    inTouchContainer2: makeNodeComponent("inTouchContainer2"),
    h1: makeNodeComponent("h1"),
    contactContainer: makeNodeComponent("contactContainer"),
    emailFull: makeNodeComponent("emailFull"),
    emailContianer: makeNodeComponent("emailContianer"),
    emailAddress: makeNodeComponent("emailAddress"),
    callMeStack: makeNodeComponent("callMeStack"),
    phoneContainer: makeNodeComponent("phoneContainer"),

    // Metadata about props expected for PlasmicWebsiteFooter
    internalVariantProps: PlasmicWebsiteFooter__VariantProps,
    internalArgProps: PlasmicWebsiteFooter__ArgProps
  }
);

export default PlasmicWebsiteFooter;
/* prettier-ignore-end */
