/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1MA8tVtTQ6ARhYAYML2fXH
// Component: GyC_5n7cwYA0

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdTextArea } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdTextArea_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/styleTokensProvider
import { config } from "@/lib/config"; // MANUALLY ADDED: re-add after npx plasmic sync

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 1MA8tVtTQ6ARhYAYML2fXH/projectcss
import sty from "./PlasmicContact.module.css"; // plasmic-import: GyC_5n7cwYA0/css

import ArrowBigRightFilledIcon from "./icons/PlasmicIcon__ArrowBigRightFilled"; // plasmic-import: 0wqLWqJgujDl/icon
import ArrowBigRightFilledIcon2 from "../library_tabler_3_2_icons/icons/PlasmicIcon__ArrowBigRightFilled"; // plasmic-import: 6uggRkEYeTKa/icon
import BrandInstagramIcon from "./icons/PlasmicIcon__BrandInstagram"; // plasmic-import: sPs8xq4XDSB7/icon
import BrandFacebookFilledIcon from "./icons/PlasmicIcon__BrandFacebookFilled"; // plasmic-import: gYHB8kOr7qS6/icon
import BrandLinkedinIcon from "./icons/PlasmicIcon__BrandLinkedin"; // plasmic-import: YL_7Hzz6ddJB/icon
import BrandGithubFilledIcon from "./icons/PlasmicIcon__BrandGithubFilled"; // plasmic-import: jgc3Mi7tL_Sx/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q: any, $ctx: any) {
  return {
    title: "Contact",

    openGraph: {
      title: "Contact"
    },
    twitter: {
      card: "summary",
      title: "Contact"
    }
  };
}

createPlasmicElementProxy;

export type PlasmicContact__VariantMembers = {};
export type PlasmicContact__VariantsArgs = {};
type VariantPropType = keyof PlasmicContact__VariantsArgs;
export const PlasmicContact__VariantProps = new Array<VariantPropType>();

export type PlasmicContact__ArgsType = {};
type ArgPropType = keyof PlasmicContact__ArgsType;
export const PlasmicContact__ArgProps = new Array<ArgPropType>();

export type PlasmicContact__OverridesType = {
  mainPage?: Flex__<"div">;
  pagesLinksContainer?: Flex__<"div">;
  link?: Flex__<"a"> & Partial<LinkProps>;
  projects?: Flex__<"a"> & Partial<LinkProps>;
  aboutLink?: Flex__<"a"> & Partial<LinkProps>;
  skills?: Flex__<"a"> & Partial<LinkProps>;
  resume?: Flex__<"a"> & Partial<LinkProps>;
  contact?: Flex__<"a"> & Partial<LinkProps>;
  img?: Flex__<typeof PlasmicImg__>;
  callMeStack?: Flex__<"div">;
  phoneContainer?: Flex__<"div">;
  emailFull?: Flex__<"div">;
  emailContianer?: Flex__<"div">;
  emailAddress?: Flex__<"div">;
  form?: Flex__<typeof FormWrapper>;
  input?: Flex__<typeof AntdInput>;
  input2?: Flex__<typeof AntdInput>;
  input3?: Flex__<typeof AntdInput>;
  textArea?: Flex__<typeof AntdTextArea>;
  button?: Flex__<typeof AntdButton>;
  socialMediaContainer?: Flex__<"div">;
  instagramLink?: Flex__<"a"> & Partial<LinkProps>;
  facebookLink?: Flex__<"a"> & Partial<LinkProps>;
  linkedinLink?: Flex__<"a"> & Partial<LinkProps>;
  githubLink?: Flex__<"a"> & Partial<LinkProps>;
};

export interface DefaultContactProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicContact__RenderFunc(props: {
  variants: PlasmicContact__VariantsArgs;
  args: PlasmicContact__ArgsType;
  overrides: PlasmicContact__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const $globalActions = useGlobalActions?.();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "form.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        refName: "form",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "form.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false,

        refName: "form",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "input.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "input2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "input3.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "textArea.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdTextArea_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });
  const dataSourcesCtx = usePlasmicDataSourceContext();
  const plasmicInvalidate = usePlasmicInvalidate();

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"mainPage"}
          data-plasmic-override={overrides.mainPage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.mainPage
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__xtLc)}>
            <div
              data-plasmic-name={"pagesLinksContainer"}
              data-plasmic-override={overrides.pagesLinksContainer}
              className={classNames(projectcss.all, sty.pagesLinksContainer)}
            >
              <PlasmicLink__
                data-plasmic-name={"link"}
                data-plasmic-override={overrides.link}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link
                )}
                component={Link}
                href={`/`}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"HOME"}
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"projects"}
                data-plasmic-override={overrides.projects}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.projects
                )}
                component={Link}
                href={`/work-experience`}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"Work Experience"}
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"aboutLink"}
                data-plasmic-override={overrides.aboutLink}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.aboutLink
                )}
                component={Link}
                href={`/about-me`}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"About Me"}
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"skills"}
                data-plasmic-override={overrides.skills}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.skills
                )}
                component={Link}
                href={`/skills`}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"Skills"}
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"resume"}
                data-plasmic-override={overrides.resume}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.resume
                )}
                component={Link}
                href={`/resume`}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"Resume"}
              </PlasmicLink__>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__kvifR)} />

            <PlasmicLink__
              data-plasmic-name={"contact"}
              data-plasmic-override={overrides.contact}
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.contact
              )}
              component={Link}
              href={`/contact`}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Contact Me"}
            </PlasmicLink__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__el4L)}>
            <div className={classNames(projectcss.all, sty.freeBox__pgzkD)}>
              <PlasmicImg__
                data-plasmic-name={"img"}
                data-plasmic-override={overrides.img}
                alt={""}
                className={classNames(sty.img)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/amir_ghahari_website/images/img7121Jpg.jpg",
                  fullWidth: 3024,
                  fullHeight: 4032,
                  aspectRatio: undefined
                }}
              />
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__bbaX9)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pQCdC
                )}
              >
                {"Get in touch with me"}
              </div>
              <div
                data-plasmic-name={"callMeStack"}
                data-plasmic-override={overrides.callMeStack}
                className={classNames(projectcss.all, sty.callMeStack)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xmFtz
                  )}
                >
                  {"Call me:"}
                </div>
                <div
                  data-plasmic-name={"phoneContainer"}
                  data-plasmic-override={overrides.phoneContainer}
                  className={classNames(projectcss.all, sty.phoneContainer)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__meWlz
                    )}
                  >
                    {config.phone}
                  </div>
                  <ArrowBigRightFilledIcon
                    className={classNames(projectcss.all, sty.svg__mGLzj)}
                    role={"img"}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"emailFull"}
                data-plasmic-override={overrides.emailFull}
                className={classNames(projectcss.all, sty.emailFull)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mVi7
                  )}
                >
                  {"Email Me:"}
                </div>
                <div
                  data-plasmic-name={"emailContianer"}
                  data-plasmic-override={overrides.emailContianer}
                  className={classNames(projectcss.all, sty.emailContianer)}
                >
                  <div
                    data-plasmic-name={"emailAddress"}
                    data-plasmic-override={overrides.emailAddress}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.emailAddress
                    )}
                  >
                    {config.email}
                  </div>
                  <ArrowBigRightFilledIcon
                    className={classNames(projectcss.all, sty.svg__nv1CB)}
                    role={"img"}
                  />
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___47SJ
                )}
              >
                {"Or"}
              </div>
              {(() => {
                const child$Props = {
                  className: classNames("__wab_instance", sty.form),
                  extendedOnValuesChange: async (...eventArgs: any) => {
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "value",
                      ["form", "value"],
                      FormWrapper_Helpers
                    ).apply(null, eventArgs);
                  },
                  formItems: [
                    { label: "Name", name: "name", inputType: "Text" },
                    {
                      label: "Message",
                      name: "message",
                      inputType: "Text Area"
                    }
                  ],
                  labelCol: (() => {
                    const __composite = {
                      span: null,
                      horizontalOnly: null,
                      offset: null
                    };
                    __composite["span"] = 15;
                    __composite["horizontalOnly"] = true;
                    __composite["offset"] = 10;
                    return __composite;
                  })(),

                  layout: "vertical",
                  mode: "advanced",
                  onFinish: async values => {
                    const $steps = {};

                    $steps["apiServerContactPost"] = true
                      ? (async () => {
                          try {
                            const response = await fetch(config.contactApiUrl, {
                              method: "POST",
                              headers: { "Content-Type": "application/json" },
                              body: JSON.stringify($state.form.value)
                            });
                            const data = await response.json();
                            return { data };
                          } catch (e) {
                            throw e;
                          }
                        })()
                      : undefined;
                    if (
                      $steps["apiServerContactPost"] != null &&
                      typeof $steps["apiServerContactPost"] === "object" &&
                      typeof $steps["apiServerContactPost"].then === "function"
                    ) {
                      $steps["apiServerContactPost"] =
                        await $steps["apiServerContactPost"];
                    }

                    $steps["runActionOnForm"] = true
                      ? (() => {
                          const actionArgs = {
                            tplRef: "form",
                            action: "clearFields"
                          };
                          return (({ tplRef, action, args }) => {
                            return $refs?.[tplRef]?.[action]?.(...(args ?? []));
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["runActionOnForm"] != null &&
                      typeof $steps["runActionOnForm"] === "object" &&
                      typeof $steps["runActionOnForm"].then === "function"
                    ) {
                      $steps["runActionOnForm"] =
                        await $steps["runActionOnForm"];
                    }

                    $steps["invokeGlobalAction"] = true
                      ? (() => {
                          const actionArgs = {
                            args: [
                              undefined,
                              "Thanks for your Message",
                              ``,
                              5,
                              "top"
                            ]
                          };
                          return $globalActions[
                            "plasmic-antd5-config-provider.showNotification"
                          ]?.apply(null, [...actionArgs.args]);
                        })()
                      : undefined;
                    if (
                      $steps["invokeGlobalAction"] != null &&
                      typeof $steps["invokeGlobalAction"] === "object" &&
                      typeof $steps["invokeGlobalAction"].then === "function"
                    ) {
                      $steps["invokeGlobalAction"] =
                        await $steps["invokeGlobalAction"];
                    }
                  },
                  onFinishFailed: async data => {
                    const $steps = {};

                    $steps["invokeGlobalAction"] = true
                      ? (() => {
                          const actionArgs = {
                            args: [
                              undefined,
                              "Please Provide Correct values for the Fields",
                              ``,
                              5,
                              "top"
                            ]
                          };
                          return $globalActions[
                            "plasmic-antd5-config-provider.showNotification"
                          ]?.apply(null, [...actionArgs.args]);
                        })()
                      : undefined;
                    if (
                      $steps["invokeGlobalAction"] != null &&
                      typeof $steps["invokeGlobalAction"] === "object" &&
                      typeof $steps["invokeGlobalAction"].then === "function"
                    ) {
                      $steps["invokeGlobalAction"] =
                        await $steps["invokeGlobalAction"];
                    }

                    $steps["runActionOnForm"] = false
                      ? (() => {
                          const actionArgs = {
                            tplRef: "form",
                            action: "clearFields"
                          };
                          return (({ tplRef, action, args }) => {
                            return $refs?.[tplRef]?.[action]?.(...(args ?? []));
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["runActionOnForm"] != null &&
                      typeof $steps["runActionOnForm"] === "object" &&
                      typeof $steps["runActionOnForm"].then === "function"
                    ) {
                      $steps["runActionOnForm"] =
                        await $steps["runActionOnForm"];
                    }
                  },
                  onIsSubmittingChange: async (...eventArgs: any) => {
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "isSubmitting",
                      ["form", "isSubmitting"],
                      FormWrapper_Helpers
                    ).apply(null, eventArgs);
                  },
                  ref: ref => {
                    $refs["form"] = ref;
                  },
                  requiredMark: true,
                  submitSlot: null,
                  wrapperCol: (() => {
                    const __composite = { span: null, horizontalOnly: true };
                    __composite["span"] = 12;
                    return __composite;
                  })()
                };
                initializeCodeComponentStates(
                  $state,
                  [
                    {
                      name: "value",
                      plasmicStateName: "form.value"
                    },
                    {
                      name: "isSubmitting",
                      plasmicStateName: "form.isSubmitting"
                    }
                  ],
                  [],
                  FormWrapper_Helpers ?? {},
                  child$Props
                );

                return (
                  <FormWrapper
                    data-plasmic-name={"form"}
                    data-plasmic-override={overrides.form}
                    {...child$Props}
                  >
                    <FormItemWrapper
                      className={classNames(
                        "__wab_instance",
                        sty.formField__kRyl
                      )}
                      hidden={false}
                      initialValue={``}
                      label={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__bzklz
                          )}
                        >
                          {"Name"}
                        </div>
                      }
                      name={"name"}
                      noLabel={false}
                      rules={[
                        {
                          ruleType: "required",
                          message: "Please Provide a Name"
                        }
                      ]}
                    >
                      {(() => {
                        const child$Props = {
                          allowClear: true,
                          autoFocus: false,
                          bordered: true,
                          className: classNames("__wab_instance", sty.input),
                          disabled: false,
                          maxLength: 70,
                          onChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["input", "value"],
                              AntdInput_Helpers
                            ).apply(null, eventArgs);
                          },
                          placeholder: ``,
                          size: "middle",
                          value: generateStateValueProp($state, [
                            "input",
                            "value"
                          ])
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "input.value"
                            }
                          ],
                          [],
                          AntdInput_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <AntdInput
                            data-plasmic-name={"input"}
                            data-plasmic-override={overrides.input}
                            {...child$Props}
                          />
                        );
                      })()}
                    </FormItemWrapper>
                    <FormItemWrapper
                      className={classNames(
                        "__wab_instance",
                        sty.formField__kINwc
                      )}
                      initialValue={``}
                      label={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__aGi4J
                          )}
                        >
                          {"Email Address"}
                        </div>
                      }
                      name={"email"}
                      noLabel={false}
                      rules={[
                        {
                          ruleType: "required",
                          message: "Please Provide an Email"
                        }
                      ]}
                    >
                      {(() => {
                        const child$Props = {
                          allowClear: true,
                          className: classNames("__wab_instance", sty.input2),
                          maxLength: 70,
                          onChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["input2", "value"],
                              AntdInput_Helpers
                            ).apply(null, eventArgs);
                          },
                          placeholder: ``,
                          size: "middle",
                          value: generateStateValueProp($state, [
                            "input2",
                            "value"
                          ])
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "input2.value"
                            }
                          ],
                          [],
                          AntdInput_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <AntdInput
                            data-plasmic-name={"input2"}
                            data-plasmic-override={overrides.input2}
                            {...child$Props}
                          />
                        );
                      })()}
                    </FormItemWrapper>
                    <FormItemWrapper
                      className={classNames(
                        "__wab_instance",
                        sty.formField__pwRpY
                      )}
                      initialValue={``}
                      label={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__uNzyB
                          )}
                        >
                          {"Subject"}
                        </div>
                      }
                      name={"subject"}
                      noLabel={false}
                      rules={[
                        {
                          ruleType: "required",
                          message: "Please Provide a Subject"
                        }
                      ]}
                    >
                      {(() => {
                        const child$Props = {
                          allowClear: true,
                          className: classNames("__wab_instance", sty.input3),
                          maxLength: 200,
                          onChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["input3", "value"],
                              AntdInput_Helpers
                            ).apply(null, eventArgs);
                          },
                          size: "middle",
                          value: generateStateValueProp($state, [
                            "input3",
                            "value"
                          ])
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "input3.value"
                            }
                          ],
                          [],
                          AntdInput_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <AntdInput
                            data-plasmic-name={"input3"}
                            data-plasmic-override={overrides.input3}
                            {...child$Props}
                          />
                        );
                      })()}
                    </FormItemWrapper>
                    <FormItemWrapper
                      className={classNames(
                        "__wab_instance",
                        sty.formField__pyQ5
                      )}
                      initialValue={``}
                      label={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zRw1O
                          )}
                        >
                          {"Message"}
                        </div>
                      }
                      name={"message"}
                      noLabel={false}
                      rules={[
                        {
                          ruleType: "required",
                          message: "Please Provide a Message"
                        }
                      ]}
                    >
                      {(() => {
                        const child$Props = {
                          autoSize: false,
                          bordered: true,
                          className: classNames("__wab_instance", sty.textArea),
                          disabled: false,
                          maxLength: 500,
                          onChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["textArea", "value"],
                              AntdTextArea_Helpers
                            ).apply(null, eventArgs);
                          },
                          placeholder: ``,
                          value: generateStateValueProp($state, [
                            "textArea",
                            "value"
                          ])
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "textArea.value"
                            }
                          ],
                          [],
                          AntdTextArea_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <AntdTextArea
                            data-plasmic-name={"textArea"}
                            data-plasmic-override={overrides.textArea}
                            {...child$Props}
                          />
                        );
                      })()}
                    </FormItemWrapper>
                    <AntdButton
                      data-plasmic-name={"button"}
                      data-plasmic-override={overrides.button}
                      className={classNames("__wab_instance", sty.button)}
                      ghost={false}
                      onClick={async () => {
                        const $steps = {};

                        $steps["refreshData"] = true
                          ? (() => {
                              const actionArgs = {
                                queryInvalidation: (() => {
                                  try {
                                    return undefined;
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return [];
                                    }
                                    throw e;
                                  }
                                })()
                              };
                              return (async ({ queryInvalidation }) => {
                                if (!queryInvalidation) {
                                  return;
                                }
                                await plasmicInvalidate(queryInvalidation);
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["refreshData"] != null &&
                          typeof $steps["refreshData"] === "object" &&
                          typeof $steps["refreshData"].then === "function"
                        ) {
                          $steps["refreshData"] = await $steps["refreshData"];
                        }
                      }}
                      shape={"round"}
                      size={"large"}
                      submitsForm={true}
                      type={"default"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__inIoj
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___223Cz
                          )}
                        >
                          {"CONTACT ME"}
                        </div>
                        <ArrowBigRightFilledIcon2
                          className={classNames(
                            projectcss.all,
                            sty.svg___5H6H0
                          )}
                          role={"img"}
                        />
                      </div>
                    </AntdButton>
                  </FormWrapper>
                );
              })()}
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___0NwXg)}>
            <div
              data-plasmic-name={"socialMediaContainer"}
              data-plasmic-override={overrides.socialMediaContainer}
              className={classNames(projectcss.all, sty.socialMediaContainer)}
            >
              <PlasmicLink__
                data-plasmic-name={"instagramLink"}
                data-plasmic-override={overrides.instagramLink}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.instagramLink
                )}
                component={Link}
                href={config.instagram}
                legacyBehavior={false}
                platform={"nextjs"}
                target={"_blank"}
              >
                <BrandInstagramIcon
                  className={classNames(projectcss.all, sty.svg__hUp)}
                  role={"img"}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"facebookLink"}
                data-plasmic-override={overrides.facebookLink}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.facebookLink
                )}
                component={Link}
                href={config.facebook}
                legacyBehavior={false}
                platform={"nextjs"}
                target={"_blank"}
              >
                <BrandFacebookFilledIcon
                  className={classNames(projectcss.all, sty.svg__f0B0)}
                  role={"img"}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"linkedinLink"}
                data-plasmic-override={overrides.linkedinLink}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.linkedinLink
                )}
                component={Link}
                href={config.linkedin}
                legacyBehavior={false}
                platform={"nextjs"}
                target={"_blank"}
              >
                <BrandLinkedinIcon
                  className={classNames(projectcss.all, sty.svg__ekJ7J)}
                  role={"img"}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"githubLink"}
                data-plasmic-override={overrides.githubLink}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.githubLink
                )}
                component={Link}
                href={config.github}
                legacyBehavior={false}
                platform={"nextjs"}
                target={"_blank"}
              >
                <BrandGithubFilledIcon
                  className={classNames(projectcss.all, sty.svg__pmwki)}
                  role={"img"}
                />
              </PlasmicLink__>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  mainPage: [
    "mainPage",
    "pagesLinksContainer",
    "link",
    "projects",
    "aboutLink",
    "skills",
    "resume",
    "contact",
    "img",
    "callMeStack",
    "phoneContainer",
    "emailFull",
    "emailContianer",
    "emailAddress",
    "form",
    "input",
    "input2",
    "input3",
    "textArea",
    "button",
    "socialMediaContainer",
    "instagramLink",
    "facebookLink",
    "linkedinLink",
    "githubLink"
  ],
  pagesLinksContainer: [
    "pagesLinksContainer",
    "link",
    "projects",
    "aboutLink",
    "skills",
    "resume"
  ],
  link: ["link"],
  projects: ["projects"],
  aboutLink: ["aboutLink"],
  skills: ["skills"],
  resume: ["resume"],
  contact: ["contact"],
  img: ["img"],
  callMeStack: ["callMeStack", "phoneContainer"],
  phoneContainer: ["phoneContainer"],
  emailFull: ["emailFull", "emailContianer", "emailAddress"],
  emailContianer: ["emailContianer", "emailAddress"],
  emailAddress: ["emailAddress"],
  form: ["form", "input", "input2", "input3", "textArea", "button"],
  input: ["input"],
  input2: ["input2"],
  input3: ["input3"],
  textArea: ["textArea"],
  button: ["button"],
  socialMediaContainer: [
    "socialMediaContainer",
    "instagramLink",
    "facebookLink",
    "linkedinLink",
    "githubLink"
  ],
  instagramLink: ["instagramLink"],
  facebookLink: ["facebookLink"],
  linkedinLink: ["linkedinLink"],
  githubLink: ["githubLink"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  mainPage: "div";
  pagesLinksContainer: "div";
  link: "a";
  projects: "a";
  aboutLink: "a";
  skills: "a";
  resume: "a";
  contact: "a";
  img: typeof PlasmicImg__;
  callMeStack: "div";
  phoneContainer: "div";
  emailFull: "div";
  emailContianer: "div";
  emailAddress: "div";
  form: typeof FormWrapper;
  input: typeof AntdInput;
  input2: typeof AntdInput;
  input3: typeof AntdInput;
  textArea: typeof AntdTextArea;
  button: typeof AntdButton;
  socialMediaContainer: "div";
  instagramLink: "a";
  facebookLink: "a";
  linkedinLink: "a";
  githubLink: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicContact__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicContact__VariantsArgs;
    args?: PlasmicContact__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicContact__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicContact__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicContact__ArgProps,
          internalVariantPropNames: PlasmicContact__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicContact__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "mainPage") {
    func.displayName = "PlasmicContact";
  } else {
    func.displayName = `PlasmicContact.${nodeName}`;
  }
  return func;
}

export const PlasmicContact = Object.assign(
  // Top-level PlasmicContact renders the root element
  makeNodeComponent("mainPage"),
  {
    // Helper components rendering sub-elements
    pagesLinksContainer: makeNodeComponent("pagesLinksContainer"),
    link: makeNodeComponent("link"),
    projects: makeNodeComponent("projects"),
    aboutLink: makeNodeComponent("aboutLink"),
    skills: makeNodeComponent("skills"),
    resume: makeNodeComponent("resume"),
    contact: makeNodeComponent("contact"),
    img: makeNodeComponent("img"),
    callMeStack: makeNodeComponent("callMeStack"),
    phoneContainer: makeNodeComponent("phoneContainer"),
    emailFull: makeNodeComponent("emailFull"),
    emailContianer: makeNodeComponent("emailContianer"),
    emailAddress: makeNodeComponent("emailAddress"),
    form: makeNodeComponent("form"),
    input: makeNodeComponent("input"),
    input2: makeNodeComponent("input2"),
    input3: makeNodeComponent("input3"),
    textArea: makeNodeComponent("textArea"),
    button: makeNodeComponent("button"),
    socialMediaContainer: makeNodeComponent("socialMediaContainer"),
    instagramLink: makeNodeComponent("instagramLink"),
    facebookLink: makeNodeComponent("facebookLink"),
    linkedinLink: makeNodeComponent("linkedinLink"),
    githubLink: makeNodeComponent("githubLink"),

    // Metadata about props expected for PlasmicContact
    internalVariantProps: PlasmicContact__VariantProps,
    internalArgProps: PlasmicContact__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pagePath: "/contact",
      searchParams: {},
      params: {}
    })
  }
);

export default PlasmicContact;
/* prettier-ignore-end */
